// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nad2000/uoa-orcidhub/client/affiliations"
	"github.com/nad2000/uoa-orcidhub/client/funds"
	"github.com/nad2000/uoa-orcidhub/client/orcid_proxy"
	"github.com/nad2000/uoa-orcidhub/client/peer_reviews"
	"github.com/nad2000/uoa-orcidhub/client/tasks"
	"github.com/nad2000/uoa-orcidhub/client/token"
	"github.com/nad2000/uoa-orcidhub/client/users"
	"github.com/nad2000/uoa-orcidhub/client/webhooks"
	"github.com/nad2000/uoa-orcidhub/client/works"
)

// Default orcidhub HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "orcidhub.org.nz"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new orcidhub HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Orcidhub {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new orcidhub HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Orcidhub {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new orcidhub client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Orcidhub {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Orcidhub)
	cli.Transport = transport

	cli.Affiliations = affiliations.New(transport, formats)

	cli.Funds = funds.New(transport, formats)

	cli.OrcidProxy = orcid_proxy.New(transport, formats)

	cli.PeerReviews = peer_reviews.New(transport, formats)

	cli.Tasks = tasks.New(transport, formats)

	cli.Token = token.New(transport, formats)

	cli.Users = users.New(transport, formats)

	cli.Webhooks = webhooks.New(transport, formats)

	cli.Works = works.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Orcidhub is a client for orcidhub
type Orcidhub struct {
	Affiliations *affiliations.Client

	Funds *funds.Client

	OrcidProxy *orcid_proxy.Client

	PeerReviews *peer_reviews.Client

	Tasks *tasks.Client

	Token *token.Client

	Users *users.Client

	Webhooks *webhooks.Client

	Works *works.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Orcidhub) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Affiliations.SetTransport(transport)

	c.Funds.SetTransport(transport)

	c.OrcidProxy.SetTransport(transport)

	c.PeerReviews.SetTransport(transport)

	c.Tasks.SetTransport(transport)

	c.Token.SetTransport(transport)

	c.Users.SetTransport(transport)

	c.Webhooks.SetTransport(transport)

	c.Works.SetTransport(transport)

}
