// Code generated by go-swagger; DO NOT EDIT.

package update

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
	validate "github.com/go-openapi/validate"
)

// PostHandleHandlerFunc turns a function with the right signature into a post handle handler
type PostHandleHandlerFunc func(PostHandleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostHandleHandlerFunc) Handle(params PostHandleParams) middleware.Responder {
	return fn(params)
}

// PostHandleHandler interface for that can handle valid post handle params
type PostHandleHandler interface {
	Handle(PostHandleParams) middleware.Responder
}

// NewPostHandle creates a new http.Handler for the post handle operation
func NewPostHandle(ctx *middleware.Context, handler PostHandleHandler) *PostHandle {
	return &PostHandle{Context: ctx, Handler: handler}
}

/*PostHandle swagger:route POST /handle update postHandle

Handle employer update event

Handle employer update event.

*/
type PostHandle struct {
	Context *middleware.Context
	Handler PostHandleHandler
}

func (o *PostHandle) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostHandleParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostHandleBody post handle body
// swagger:model PostHandleBody
type PostHandleBody struct {

	// User UAID
	// Required: true
	Subject *string `json:"subject"`
}

// Validate validates this post handle body
func (o *PostHandleBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSubject(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostHandleBody) validateSubject(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"subject", "body", o.Subject); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostHandleBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostHandleBody) UnmarshalBinary(b []byte) error {
	var res PostHandleBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
