// Code generated by go-swagger; DO NOT EDIT.

package update

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostHandleCreatedCode is the HTTP code returned for type PostHandleCreated
const PostHandleCreatedCode int = 201

/*PostHandleCreated OK

swagger:response postHandleCreated
*/
type PostHandleCreated struct {
}

// NewPostHandleCreated creates PostHandleCreated with default headers values
func NewPostHandleCreated() *PostHandleCreated {

	return &PostHandleCreated{}
}

// WriteResponse to the client
func (o *PostHandleCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}
