swagger: '2.0'
info:
  version: 'v1'
  title: UoA to ORCIDHub
  description: This is UoA to ORCIDHub integration application.

# securityDefinitions:
#   implicit:
#     type: oauth2
#     # This should be updated to the Authorization URL of your OAuth provider.
#     authorizationUrl: http://example.com/oauth/auth
#     flow: implicit
#     scopes:
#       write: allows modifying resources
#       read: allows reading resources

security:
  - implicit:
    - read
    - write
paths:
  /handle:
    post:
      tags: 
        - update
      consumes:
        - application/json
      summary: Handle employer update event
      description: Handle employer update event.
      security: [ ]
      parameters:
        - description: Message body with AUID.
          in: body
          name: body
          schema:
            properties:
              subject:
                description: User UAID
                type: string
                format: '[0-9]{8,10}'
            required:
              - subject
      responses:
        201:
          description: OK
  /ping:
    get:
      summary: Server heartbeat operation
      description: This operation shows how to override the global security defined above, as we want to open it up for all users.
      security: [ ]
      responses:
        200:
          description: OK

# host: virtserver.swaggerhub.com
# basePath: /uoa-orcidhub/api/v1
schemes:
 - http
# Added by API Auto Mocking Plugin
basePath: /api/v1
