// Code generated by go-swagger; DO NOT EDIT.

package works

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIV10WorksTaskIDParams creates a new GetAPIV10WorksTaskIDParams object
// with the default values initialized.
func NewGetAPIV10WorksTaskIDParams() *GetAPIV10WorksTaskIDParams {
	var ()
	return &GetAPIV10WorksTaskIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV10WorksTaskIDParamsWithTimeout creates a new GetAPIV10WorksTaskIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV10WorksTaskIDParamsWithTimeout(timeout time.Duration) *GetAPIV10WorksTaskIDParams {
	var ()
	return &GetAPIV10WorksTaskIDParams{

		timeout: timeout,
	}
}

// NewGetAPIV10WorksTaskIDParamsWithContext creates a new GetAPIV10WorksTaskIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV10WorksTaskIDParamsWithContext(ctx context.Context) *GetAPIV10WorksTaskIDParams {
	var ()
	return &GetAPIV10WorksTaskIDParams{

		Context: ctx,
	}
}

// NewGetAPIV10WorksTaskIDParamsWithHTTPClient creates a new GetAPIV10WorksTaskIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV10WorksTaskIDParamsWithHTTPClient(client *http.Client) *GetAPIV10WorksTaskIDParams {
	var ()
	return &GetAPIV10WorksTaskIDParams{
		HTTPClient: client,
	}
}

/*GetAPIV10WorksTaskIDParams contains all the parameters to send to the API endpoint
for the get API v10 works task ID operation typically these are written to a http.Request
*/
type GetAPIV10WorksTaskIDParams struct {

	/*TaskID
	  Work task ID.

	*/
	TaskID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v10 works task ID params
func (o *GetAPIV10WorksTaskIDParams) WithTimeout(timeout time.Duration) *GetAPIV10WorksTaskIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v10 works task ID params
func (o *GetAPIV10WorksTaskIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v10 works task ID params
func (o *GetAPIV10WorksTaskIDParams) WithContext(ctx context.Context) *GetAPIV10WorksTaskIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v10 works task ID params
func (o *GetAPIV10WorksTaskIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v10 works task ID params
func (o *GetAPIV10WorksTaskIDParams) WithHTTPClient(client *http.Client) *GetAPIV10WorksTaskIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v10 works task ID params
func (o *GetAPIV10WorksTaskIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskID adds the taskID to the get API v10 works task ID params
func (o *GetAPIV10WorksTaskIDParams) WithTaskID(taskID int64) *GetAPIV10WorksTaskIDParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get API v10 works task ID params
func (o *GetAPIV10WorksTaskIDParams) SetTaskID(taskID int64) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV10WorksTaskIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param task_id
	if err := r.SetPathParam("task_id", swag.FormatInt64(o.TaskID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
