// Code generated by go-swagger; DO NOT EDIT.

package works

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// NewPostAPIV10WorksTaskIDParams creates a new PostAPIV10WorksTaskIDParams object
// with the default values initialized.
func NewPostAPIV10WorksTaskIDParams() *PostAPIV10WorksTaskIDParams {
	var ()
	return &PostAPIV10WorksTaskIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV10WorksTaskIDParamsWithTimeout creates a new PostAPIV10WorksTaskIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV10WorksTaskIDParamsWithTimeout(timeout time.Duration) *PostAPIV10WorksTaskIDParams {
	var ()
	return &PostAPIV10WorksTaskIDParams{

		timeout: timeout,
	}
}

// NewPostAPIV10WorksTaskIDParamsWithContext creates a new PostAPIV10WorksTaskIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV10WorksTaskIDParamsWithContext(ctx context.Context) *PostAPIV10WorksTaskIDParams {
	var ()
	return &PostAPIV10WorksTaskIDParams{

		Context: ctx,
	}
}

// NewPostAPIV10WorksTaskIDParamsWithHTTPClient creates a new PostAPIV10WorksTaskIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV10WorksTaskIDParamsWithHTTPClient(client *http.Client) *PostAPIV10WorksTaskIDParams {
	var ()
	return &PostAPIV10WorksTaskIDParams{
		HTTPClient: client,
	}
}

/*PostAPIV10WorksTaskIDParams contains all the parameters to send to the API endpoint
for the post API v10 works task ID operation typically these are written to a http.Request
*/
type PostAPIV10WorksTaskIDParams struct {

	/*TaskID
	  Work task ID.

	*/
	TaskID int64
	/*WorkTask
	  Work task.

	*/
	WorkTask *models.WorkTask

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API v10 works task ID params
func (o *PostAPIV10WorksTaskIDParams) WithTimeout(timeout time.Duration) *PostAPIV10WorksTaskIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v10 works task ID params
func (o *PostAPIV10WorksTaskIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v10 works task ID params
func (o *PostAPIV10WorksTaskIDParams) WithContext(ctx context.Context) *PostAPIV10WorksTaskIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v10 works task ID params
func (o *PostAPIV10WorksTaskIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v10 works task ID params
func (o *PostAPIV10WorksTaskIDParams) WithHTTPClient(client *http.Client) *PostAPIV10WorksTaskIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v10 works task ID params
func (o *PostAPIV10WorksTaskIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskID adds the taskID to the post API v10 works task ID params
func (o *PostAPIV10WorksTaskIDParams) WithTaskID(taskID int64) *PostAPIV10WorksTaskIDParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the post API v10 works task ID params
func (o *PostAPIV10WorksTaskIDParams) SetTaskID(taskID int64) {
	o.TaskID = taskID
}

// WithWorkTask adds the workTask to the post API v10 works task ID params
func (o *PostAPIV10WorksTaskIDParams) WithWorkTask(workTask *models.WorkTask) *PostAPIV10WorksTaskIDParams {
	o.SetWorkTask(workTask)
	return o
}

// SetWorkTask adds the workTask to the post API v10 works task ID params
func (o *PostAPIV10WorksTaskIDParams) SetWorkTask(workTask *models.WorkTask) {
	o.WorkTask = workTask
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV10WorksTaskIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param task_id
	if err := r.SetPathParam("task_id", swag.FormatInt64(o.TaskID)); err != nil {
		return err
	}

	if o.WorkTask != nil {
		if err := r.SetBodyParam(o.WorkTask); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
