// Code generated by go-swagger; DO NOT EDIT.

package works

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// PostAPIV10WorksTaskIDReader is a Reader for the PostAPIV10WorksTaskID structure.
type PostAPIV10WorksTaskIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV10WorksTaskIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAPIV10WorksTaskIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostAPIV10WorksTaskIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostAPIV10WorksTaskIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostAPIV10WorksTaskIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAPIV10WorksTaskIDOK creates a PostAPIV10WorksTaskIDOK with default headers values
func NewPostAPIV10WorksTaskIDOK() *PostAPIV10WorksTaskIDOK {
	return &PostAPIV10WorksTaskIDOK{}
}

/*PostAPIV10WorksTaskIDOK handles this case with default header values.

successful operation
*/
type PostAPIV10WorksTaskIDOK struct {
	Payload *models.WorkTask
}

func (o *PostAPIV10WorksTaskIDOK) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/works/{task_id}][%d] postApiV10WorksTaskIdOK  %+v", 200, o.Payload)
}

func (o *PostAPIV10WorksTaskIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WorkTask)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10WorksTaskIDUnauthorized creates a PostAPIV10WorksTaskIDUnauthorized with default headers values
func NewPostAPIV10WorksTaskIDUnauthorized() *PostAPIV10WorksTaskIDUnauthorized {
	return &PostAPIV10WorksTaskIDUnauthorized{}
}

/*PostAPIV10WorksTaskIDUnauthorized handles this case with default header values.

Unauthorized
*/
type PostAPIV10WorksTaskIDUnauthorized struct {
	Payload *models.Error
}

func (o *PostAPIV10WorksTaskIDUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/works/{task_id}][%d] postApiV10WorksTaskIdUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAPIV10WorksTaskIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10WorksTaskIDForbidden creates a PostAPIV10WorksTaskIDForbidden with default headers values
func NewPostAPIV10WorksTaskIDForbidden() *PostAPIV10WorksTaskIDForbidden {
	return &PostAPIV10WorksTaskIDForbidden{}
}

/*PostAPIV10WorksTaskIDForbidden handles this case with default header values.

Access Denied
*/
type PostAPIV10WorksTaskIDForbidden struct {
	Payload *models.Error
}

func (o *PostAPIV10WorksTaskIDForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/works/{task_id}][%d] postApiV10WorksTaskIdForbidden  %+v", 403, o.Payload)
}

func (o *PostAPIV10WorksTaskIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10WorksTaskIDNotFound creates a PostAPIV10WorksTaskIDNotFound with default headers values
func NewPostAPIV10WorksTaskIDNotFound() *PostAPIV10WorksTaskIDNotFound {
	return &PostAPIV10WorksTaskIDNotFound{}
}

/*PostAPIV10WorksTaskIDNotFound handles this case with default header values.

The specified resource was not found
*/
type PostAPIV10WorksTaskIDNotFound struct {
	Payload *models.Error
}

func (o *PostAPIV10WorksTaskIDNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/works/{task_id}][%d] postApiV10WorksTaskIdNotFound  %+v", 404, o.Payload)
}

func (o *PostAPIV10WorksTaskIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
