// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAPIV10OrcidWebhookParams creates a new DeleteAPIV10OrcidWebhookParams object
// with the default values initialized.
func NewDeleteAPIV10OrcidWebhookParams() *DeleteAPIV10OrcidWebhookParams {
	var ()
	return &DeleteAPIV10OrcidWebhookParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV10OrcidWebhookParamsWithTimeout creates a new DeleteAPIV10OrcidWebhookParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPIV10OrcidWebhookParamsWithTimeout(timeout time.Duration) *DeleteAPIV10OrcidWebhookParams {
	var ()
	return &DeleteAPIV10OrcidWebhookParams{

		timeout: timeout,
	}
}

// NewDeleteAPIV10OrcidWebhookParamsWithContext creates a new DeleteAPIV10OrcidWebhookParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPIV10OrcidWebhookParamsWithContext(ctx context.Context) *DeleteAPIV10OrcidWebhookParams {
	var ()
	return &DeleteAPIV10OrcidWebhookParams{

		Context: ctx,
	}
}

// NewDeleteAPIV10OrcidWebhookParamsWithHTTPClient creates a new DeleteAPIV10OrcidWebhookParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPIV10OrcidWebhookParamsWithHTTPClient(client *http.Client) *DeleteAPIV10OrcidWebhookParams {
	var ()
	return &DeleteAPIV10OrcidWebhookParams{
		HTTPClient: client,
	}
}

/*DeleteAPIV10OrcidWebhookParams contains all the parameters to send to the API endpoint
for the delete API v10 orcid webhook operation typically these are written to a http.Request
*/
type DeleteAPIV10OrcidWebhookParams struct {

	/*Orcid
	  User ORCID ID.

	*/
	Orcid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete API v10 orcid webhook params
func (o *DeleteAPIV10OrcidWebhookParams) WithTimeout(timeout time.Duration) *DeleteAPIV10OrcidWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v10 orcid webhook params
func (o *DeleteAPIV10OrcidWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v10 orcid webhook params
func (o *DeleteAPIV10OrcidWebhookParams) WithContext(ctx context.Context) *DeleteAPIV10OrcidWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v10 orcid webhook params
func (o *DeleteAPIV10OrcidWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v10 orcid webhook params
func (o *DeleteAPIV10OrcidWebhookParams) WithHTTPClient(client *http.Client) *DeleteAPIV10OrcidWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v10 orcid webhook params
func (o *DeleteAPIV10OrcidWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrcid adds the orcid to the delete API v10 orcid webhook params
func (o *DeleteAPIV10OrcidWebhookParams) WithOrcid(orcid string) *DeleteAPIV10OrcidWebhookParams {
	o.SetOrcid(orcid)
	return o
}

// SetOrcid adds the orcid to the delete API v10 orcid webhook params
func (o *DeleteAPIV10OrcidWebhookParams) SetOrcid(orcid string) {
	o.Orcid = orcid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV10OrcidWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orcid
	if err := r.SetPathParam("orcid", o.Orcid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
