// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// PutAPIV10OrcidWebhookReader is a Reader for the PutAPIV10OrcidWebhook structure.
type PutAPIV10OrcidWebhookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIV10OrcidWebhookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPutAPIV10OrcidWebhookCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewPutAPIV10OrcidWebhookNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewPutAPIV10OrcidWebhookUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutAPIV10OrcidWebhookCreated creates a PutAPIV10OrcidWebhookCreated with default headers values
func NewPutAPIV10OrcidWebhookCreated() *PutAPIV10OrcidWebhookCreated {
	return &PutAPIV10OrcidWebhookCreated{}
}

/*PutAPIV10OrcidWebhookCreated handles this case with default header values.

A webhoook successfully set up.
*/
type PutAPIV10OrcidWebhookCreated struct {
}

func (o *PutAPIV10OrcidWebhookCreated) Error() string {
	return fmt.Sprintf("[PUT /api/v1.0/{orcid}/webhook][%d] putApiV10OrcidWebhookCreated ", 201)
}

func (o *PutAPIV10OrcidWebhookCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIV10OrcidWebhookNotFound creates a PutAPIV10OrcidWebhookNotFound with default headers values
func NewPutAPIV10OrcidWebhookNotFound() *PutAPIV10OrcidWebhookNotFound {
	return &PutAPIV10OrcidWebhookNotFound{}
}

/*PutAPIV10OrcidWebhookNotFound handles this case with default header values.

Invalid ORCID iD.
*/
type PutAPIV10OrcidWebhookNotFound struct {
	Payload *models.Error
}

func (o *PutAPIV10OrcidWebhookNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v1.0/{orcid}/webhook][%d] putApiV10OrcidWebhookNotFound  %+v", 404, o.Payload)
}

func (o *PutAPIV10OrcidWebhookNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIV10OrcidWebhookUnsupportedMediaType creates a PutAPIV10OrcidWebhookUnsupportedMediaType with default headers values
func NewPutAPIV10OrcidWebhookUnsupportedMediaType() *PutAPIV10OrcidWebhookUnsupportedMediaType {
	return &PutAPIV10OrcidWebhookUnsupportedMediaType{}
}

/*PutAPIV10OrcidWebhookUnsupportedMediaType handles this case with default header values.

Invalid call-back URL or missing ORCID iD.
*/
type PutAPIV10OrcidWebhookUnsupportedMediaType struct {
	Payload *models.Error
}

func (o *PutAPIV10OrcidWebhookUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[PUT /api/v1.0/{orcid}/webhook][%d] putApiV10OrcidWebhookUnsupportedMediaType  %+v", 415, o.Payload)
}

func (o *PutAPIV10OrcidWebhookUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
