// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutAPIV10OrcidWebhookCallbackURLParams creates a new PutAPIV10OrcidWebhookCallbackURLParams object
// with the default values initialized.
func NewPutAPIV10OrcidWebhookCallbackURLParams() *PutAPIV10OrcidWebhookCallbackURLParams {
	var ()
	return &PutAPIV10OrcidWebhookCallbackURLParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV10OrcidWebhookCallbackURLParamsWithTimeout creates a new PutAPIV10OrcidWebhookCallbackURLParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIV10OrcidWebhookCallbackURLParamsWithTimeout(timeout time.Duration) *PutAPIV10OrcidWebhookCallbackURLParams {
	var ()
	return &PutAPIV10OrcidWebhookCallbackURLParams{

		timeout: timeout,
	}
}

// NewPutAPIV10OrcidWebhookCallbackURLParamsWithContext creates a new PutAPIV10OrcidWebhookCallbackURLParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIV10OrcidWebhookCallbackURLParamsWithContext(ctx context.Context) *PutAPIV10OrcidWebhookCallbackURLParams {
	var ()
	return &PutAPIV10OrcidWebhookCallbackURLParams{

		Context: ctx,
	}
}

// NewPutAPIV10OrcidWebhookCallbackURLParamsWithHTTPClient creates a new PutAPIV10OrcidWebhookCallbackURLParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIV10OrcidWebhookCallbackURLParamsWithHTTPClient(client *http.Client) *PutAPIV10OrcidWebhookCallbackURLParams {
	var ()
	return &PutAPIV10OrcidWebhookCallbackURLParams{
		HTTPClient: client,
	}
}

/*PutAPIV10OrcidWebhookCallbackURLParams contains all the parameters to send to the API endpoint
for the put API v10 orcid webhook callback URL operation typically these are written to a http.Request
*/
type PutAPIV10OrcidWebhookCallbackURLParams struct {

	/*CallbackURL
	  The call-back URL that will receive a POST request when an update of a ORCID profile occurs.

	*/
	CallbackURL string
	/*Orcid
	  User ORCID ID.

	*/
	Orcid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put API v10 orcid webhook callback URL params
func (o *PutAPIV10OrcidWebhookCallbackURLParams) WithTimeout(timeout time.Duration) *PutAPIV10OrcidWebhookCallbackURLParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v10 orcid webhook callback URL params
func (o *PutAPIV10OrcidWebhookCallbackURLParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v10 orcid webhook callback URL params
func (o *PutAPIV10OrcidWebhookCallbackURLParams) WithContext(ctx context.Context) *PutAPIV10OrcidWebhookCallbackURLParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v10 orcid webhook callback URL params
func (o *PutAPIV10OrcidWebhookCallbackURLParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v10 orcid webhook callback URL params
func (o *PutAPIV10OrcidWebhookCallbackURLParams) WithHTTPClient(client *http.Client) *PutAPIV10OrcidWebhookCallbackURLParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v10 orcid webhook callback URL params
func (o *PutAPIV10OrcidWebhookCallbackURLParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCallbackURL adds the callbackURL to the put API v10 orcid webhook callback URL params
func (o *PutAPIV10OrcidWebhookCallbackURLParams) WithCallbackURL(callbackURL string) *PutAPIV10OrcidWebhookCallbackURLParams {
	o.SetCallbackURL(callbackURL)
	return o
}

// SetCallbackURL adds the callbackUrl to the put API v10 orcid webhook callback URL params
func (o *PutAPIV10OrcidWebhookCallbackURLParams) SetCallbackURL(callbackURL string) {
	o.CallbackURL = callbackURL
}

// WithOrcid adds the orcid to the put API v10 orcid webhook callback URL params
func (o *PutAPIV10OrcidWebhookCallbackURLParams) WithOrcid(orcid string) *PutAPIV10OrcidWebhookCallbackURLParams {
	o.SetOrcid(orcid)
	return o
}

// SetOrcid adds the orcid to the put API v10 orcid webhook callback URL params
func (o *PutAPIV10OrcidWebhookCallbackURLParams) SetOrcid(orcid string) {
	o.Orcid = orcid
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV10OrcidWebhookCallbackURLParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param callback_url
	if err := r.SetPathParam("callback_url", o.CallbackURL); err != nil {
		return err
	}

	// path param orcid
	if err := r.SetPathParam("orcid", o.Orcid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
