// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutAPIV10OrcidWebhookParams creates a new PutAPIV10OrcidWebhookParams object
// with the default values initialized.
func NewPutAPIV10OrcidWebhookParams() *PutAPIV10OrcidWebhookParams {
	var ()
	return &PutAPIV10OrcidWebhookParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV10OrcidWebhookParamsWithTimeout creates a new PutAPIV10OrcidWebhookParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIV10OrcidWebhookParamsWithTimeout(timeout time.Duration) *PutAPIV10OrcidWebhookParams {
	var ()
	return &PutAPIV10OrcidWebhookParams{

		timeout: timeout,
	}
}

// NewPutAPIV10OrcidWebhookParamsWithContext creates a new PutAPIV10OrcidWebhookParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIV10OrcidWebhookParamsWithContext(ctx context.Context) *PutAPIV10OrcidWebhookParams {
	var ()
	return &PutAPIV10OrcidWebhookParams{

		Context: ctx,
	}
}

// NewPutAPIV10OrcidWebhookParamsWithHTTPClient creates a new PutAPIV10OrcidWebhookParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIV10OrcidWebhookParamsWithHTTPClient(client *http.Client) *PutAPIV10OrcidWebhookParams {
	var ()
	return &PutAPIV10OrcidWebhookParams{
		HTTPClient: client,
	}
}

/*PutAPIV10OrcidWebhookParams contains all the parameters to send to the API endpoint
for the put API v10 orcid webhook operation typically these are written to a http.Request
*/
type PutAPIV10OrcidWebhookParams struct {

	/*Orcid
	  User ORCID ID.

	*/
	Orcid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put API v10 orcid webhook params
func (o *PutAPIV10OrcidWebhookParams) WithTimeout(timeout time.Duration) *PutAPIV10OrcidWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v10 orcid webhook params
func (o *PutAPIV10OrcidWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v10 orcid webhook params
func (o *PutAPIV10OrcidWebhookParams) WithContext(ctx context.Context) *PutAPIV10OrcidWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v10 orcid webhook params
func (o *PutAPIV10OrcidWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v10 orcid webhook params
func (o *PutAPIV10OrcidWebhookParams) WithHTTPClient(client *http.Client) *PutAPIV10OrcidWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v10 orcid webhook params
func (o *PutAPIV10OrcidWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrcid adds the orcid to the put API v10 orcid webhook params
func (o *PutAPIV10OrcidWebhookParams) WithOrcid(orcid string) *PutAPIV10OrcidWebhookParams {
	o.SetOrcid(orcid)
	return o
}

// SetOrcid adds the orcid to the put API v10 orcid webhook params
func (o *PutAPIV10OrcidWebhookParams) SetOrcid(orcid string) {
	o.Orcid = orcid
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV10OrcidWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orcid
	if err := r.SetPathParam("orcid", o.Orcid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
