// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new webhooks API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for webhooks API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
DeleteAPIV10OrcidWebhook delete API v10 orcid webhook API
*/
func (a *Client) DeleteAPIV10OrcidWebhook(params *DeleteAPIV10OrcidWebhookParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteAPIV10OrcidWebhookNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteAPIV10OrcidWebhookParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DeleteAPIV10OrcidWebhook",
		Method:             "DELETE",
		PathPattern:        "/api/v1.0/{orcid}/webhook",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteAPIV10OrcidWebhookReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteAPIV10OrcidWebhookNoContent), nil

}

/*
DeleteAPIV10OrcidWebhookCallbackURL delete API v10 orcid webhook callback URL API
*/
func (a *Client) DeleteAPIV10OrcidWebhookCallbackURL(params *DeleteAPIV10OrcidWebhookCallbackURLParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteAPIV10OrcidWebhookCallbackURLNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteAPIV10OrcidWebhookCallbackURLParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DeleteAPIV10OrcidWebhookCallbackURL",
		Method:             "DELETE",
		PathPattern:        "/api/v1.0/{orcid}/webhook/{callback_url}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteAPIV10OrcidWebhookCallbackURLReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteAPIV10OrcidWebhookCallbackURLNoContent), nil

}

/*
PutAPIV10OrcidWebhook put API v10 orcid webhook API
*/
func (a *Client) PutAPIV10OrcidWebhook(params *PutAPIV10OrcidWebhookParams, authInfo runtime.ClientAuthInfoWriter) (*PutAPIV10OrcidWebhookCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutAPIV10OrcidWebhookParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PutAPIV10OrcidWebhook",
		Method:             "PUT",
		PathPattern:        "/api/v1.0/{orcid}/webhook",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PutAPIV10OrcidWebhookReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PutAPIV10OrcidWebhookCreated), nil

}

/*
PutAPIV10OrcidWebhookCallbackURL put API v10 orcid webhook callback URL API
*/
func (a *Client) PutAPIV10OrcidWebhookCallbackURL(params *PutAPIV10OrcidWebhookCallbackURLParams, authInfo runtime.ClientAuthInfoWriter) (*PutAPIV10OrcidWebhookCallbackURLCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutAPIV10OrcidWebhookCallbackURLParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PutAPIV10OrcidWebhookCallbackURL",
		Method:             "PUT",
		PathPattern:        "/api/v1.0/{orcid}/webhook/{callback_url}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PutAPIV10OrcidWebhookCallbackURLReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PutAPIV10OrcidWebhookCallbackURLCreated), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
