// Code generated by go-swagger; DO NOT EDIT.

package orcid_proxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteOrcidAPIVersionOrcidPathParams creates a new DeleteOrcidAPIVersionOrcidPathParams object
// with the default values initialized.
func NewDeleteOrcidAPIVersionOrcidPathParams() *DeleteOrcidAPIVersionOrcidPathParams {
	var ()
	return &DeleteOrcidAPIVersionOrcidPathParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOrcidAPIVersionOrcidPathParamsWithTimeout creates a new DeleteOrcidAPIVersionOrcidPathParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteOrcidAPIVersionOrcidPathParamsWithTimeout(timeout time.Duration) *DeleteOrcidAPIVersionOrcidPathParams {
	var ()
	return &DeleteOrcidAPIVersionOrcidPathParams{

		timeout: timeout,
	}
}

// NewDeleteOrcidAPIVersionOrcidPathParamsWithContext creates a new DeleteOrcidAPIVersionOrcidPathParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteOrcidAPIVersionOrcidPathParamsWithContext(ctx context.Context) *DeleteOrcidAPIVersionOrcidPathParams {
	var ()
	return &DeleteOrcidAPIVersionOrcidPathParams{

		Context: ctx,
	}
}

// NewDeleteOrcidAPIVersionOrcidPathParamsWithHTTPClient creates a new DeleteOrcidAPIVersionOrcidPathParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteOrcidAPIVersionOrcidPathParamsWithHTTPClient(client *http.Client) *DeleteOrcidAPIVersionOrcidPathParams {
	var ()
	return &DeleteOrcidAPIVersionOrcidPathParams{
		HTTPClient: client,
	}
}

/*DeleteOrcidAPIVersionOrcidPathParams contains all the parameters to send to the API endpoint
for the delete orcid API version orcid path operation typically these are written to a http.Request
*/
type DeleteOrcidAPIVersionOrcidPathParams struct {

	/*Orcid
	  User ORCID ID.

	*/
	Orcid string
	/*Path
	  The rest of the ORCID API entry point URL.

	*/
	Path string
	/*Version
	  ORCID API version

	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete orcid API version orcid path params
func (o *DeleteOrcidAPIVersionOrcidPathParams) WithTimeout(timeout time.Duration) *DeleteOrcidAPIVersionOrcidPathParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete orcid API version orcid path params
func (o *DeleteOrcidAPIVersionOrcidPathParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete orcid API version orcid path params
func (o *DeleteOrcidAPIVersionOrcidPathParams) WithContext(ctx context.Context) *DeleteOrcidAPIVersionOrcidPathParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete orcid API version orcid path params
func (o *DeleteOrcidAPIVersionOrcidPathParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete orcid API version orcid path params
func (o *DeleteOrcidAPIVersionOrcidPathParams) WithHTTPClient(client *http.Client) *DeleteOrcidAPIVersionOrcidPathParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete orcid API version orcid path params
func (o *DeleteOrcidAPIVersionOrcidPathParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrcid adds the orcid to the delete orcid API version orcid path params
func (o *DeleteOrcidAPIVersionOrcidPathParams) WithOrcid(orcid string) *DeleteOrcidAPIVersionOrcidPathParams {
	o.SetOrcid(orcid)
	return o
}

// SetOrcid adds the orcid to the delete orcid API version orcid path params
func (o *DeleteOrcidAPIVersionOrcidPathParams) SetOrcid(orcid string) {
	o.Orcid = orcid
}

// WithPath adds the path to the delete orcid API version orcid path params
func (o *DeleteOrcidAPIVersionOrcidPathParams) WithPath(path string) *DeleteOrcidAPIVersionOrcidPathParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the delete orcid API version orcid path params
func (o *DeleteOrcidAPIVersionOrcidPathParams) SetPath(path string) {
	o.Path = path
}

// WithVersion adds the version to the delete orcid API version orcid path params
func (o *DeleteOrcidAPIVersionOrcidPathParams) WithVersion(version string) *DeleteOrcidAPIVersionOrcidPathParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the delete orcid API version orcid path params
func (o *DeleteOrcidAPIVersionOrcidPathParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrcidAPIVersionOrcidPathParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orcid
	if err := r.SetPathParam("orcid", o.Orcid); err != nil {
		return err
	}

	// path param path
	if err := r.SetPathParam("path", o.Path); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
