// Code generated by go-swagger; DO NOT EDIT.

package orcid_proxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrcidAPIVersionOrcidParams creates a new GetOrcidAPIVersionOrcidParams object
// with the default values initialized.
func NewGetOrcidAPIVersionOrcidParams() *GetOrcidAPIVersionOrcidParams {
	var ()
	return &GetOrcidAPIVersionOrcidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrcidAPIVersionOrcidParamsWithTimeout creates a new GetOrcidAPIVersionOrcidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrcidAPIVersionOrcidParamsWithTimeout(timeout time.Duration) *GetOrcidAPIVersionOrcidParams {
	var ()
	return &GetOrcidAPIVersionOrcidParams{

		timeout: timeout,
	}
}

// NewGetOrcidAPIVersionOrcidParamsWithContext creates a new GetOrcidAPIVersionOrcidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrcidAPIVersionOrcidParamsWithContext(ctx context.Context) *GetOrcidAPIVersionOrcidParams {
	var ()
	return &GetOrcidAPIVersionOrcidParams{

		Context: ctx,
	}
}

// NewGetOrcidAPIVersionOrcidParamsWithHTTPClient creates a new GetOrcidAPIVersionOrcidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrcidAPIVersionOrcidParamsWithHTTPClient(client *http.Client) *GetOrcidAPIVersionOrcidParams {
	var ()
	return &GetOrcidAPIVersionOrcidParams{
		HTTPClient: client,
	}
}

/*GetOrcidAPIVersionOrcidParams contains all the parameters to send to the API endpoint
for the get orcid API version orcid operation typically these are written to a http.Request
*/
type GetOrcidAPIVersionOrcidParams struct {

	/*Orcid
	  User ORCID ID.

	*/
	Orcid string
	/*Version
	  ORCID API version

	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get orcid API version orcid params
func (o *GetOrcidAPIVersionOrcidParams) WithTimeout(timeout time.Duration) *GetOrcidAPIVersionOrcidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get orcid API version orcid params
func (o *GetOrcidAPIVersionOrcidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get orcid API version orcid params
func (o *GetOrcidAPIVersionOrcidParams) WithContext(ctx context.Context) *GetOrcidAPIVersionOrcidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get orcid API version orcid params
func (o *GetOrcidAPIVersionOrcidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get orcid API version orcid params
func (o *GetOrcidAPIVersionOrcidParams) WithHTTPClient(client *http.Client) *GetOrcidAPIVersionOrcidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get orcid API version orcid params
func (o *GetOrcidAPIVersionOrcidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrcid adds the orcid to the get orcid API version orcid params
func (o *GetOrcidAPIVersionOrcidParams) WithOrcid(orcid string) *GetOrcidAPIVersionOrcidParams {
	o.SetOrcid(orcid)
	return o
}

// SetOrcid adds the orcid to the get orcid API version orcid params
func (o *GetOrcidAPIVersionOrcidParams) SetOrcid(orcid string) {
	o.Orcid = orcid
}

// WithVersion adds the version to the get orcid API version orcid params
func (o *GetOrcidAPIVersionOrcidParams) WithVersion(version string) *GetOrcidAPIVersionOrcidParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get orcid API version orcid params
func (o *GetOrcidAPIVersionOrcidParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrcidAPIVersionOrcidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orcid
	if err := r.SetPathParam("orcid", o.Orcid); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
