// Code generated by go-swagger; DO NOT EDIT.

package orcid_proxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrcidAPIVersionOrcidPathParams creates a new GetOrcidAPIVersionOrcidPathParams object
// with the default values initialized.
func NewGetOrcidAPIVersionOrcidPathParams() *GetOrcidAPIVersionOrcidPathParams {
	var ()
	return &GetOrcidAPIVersionOrcidPathParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrcidAPIVersionOrcidPathParamsWithTimeout creates a new GetOrcidAPIVersionOrcidPathParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrcidAPIVersionOrcidPathParamsWithTimeout(timeout time.Duration) *GetOrcidAPIVersionOrcidPathParams {
	var ()
	return &GetOrcidAPIVersionOrcidPathParams{

		timeout: timeout,
	}
}

// NewGetOrcidAPIVersionOrcidPathParamsWithContext creates a new GetOrcidAPIVersionOrcidPathParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrcidAPIVersionOrcidPathParamsWithContext(ctx context.Context) *GetOrcidAPIVersionOrcidPathParams {
	var ()
	return &GetOrcidAPIVersionOrcidPathParams{

		Context: ctx,
	}
}

// NewGetOrcidAPIVersionOrcidPathParamsWithHTTPClient creates a new GetOrcidAPIVersionOrcidPathParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrcidAPIVersionOrcidPathParamsWithHTTPClient(client *http.Client) *GetOrcidAPIVersionOrcidPathParams {
	var ()
	return &GetOrcidAPIVersionOrcidPathParams{
		HTTPClient: client,
	}
}

/*GetOrcidAPIVersionOrcidPathParams contains all the parameters to send to the API endpoint
for the get orcid API version orcid path operation typically these are written to a http.Request
*/
type GetOrcidAPIVersionOrcidPathParams struct {

	/*Orcid
	  User ORCID ID.

	*/
	Orcid string
	/*Path
	  The rest of the ORCID API entry point URL.

	*/
	Path string
	/*Version
	  ORCID API version

	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get orcid API version orcid path params
func (o *GetOrcidAPIVersionOrcidPathParams) WithTimeout(timeout time.Duration) *GetOrcidAPIVersionOrcidPathParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get orcid API version orcid path params
func (o *GetOrcidAPIVersionOrcidPathParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get orcid API version orcid path params
func (o *GetOrcidAPIVersionOrcidPathParams) WithContext(ctx context.Context) *GetOrcidAPIVersionOrcidPathParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get orcid API version orcid path params
func (o *GetOrcidAPIVersionOrcidPathParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get orcid API version orcid path params
func (o *GetOrcidAPIVersionOrcidPathParams) WithHTTPClient(client *http.Client) *GetOrcidAPIVersionOrcidPathParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get orcid API version orcid path params
func (o *GetOrcidAPIVersionOrcidPathParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrcid adds the orcid to the get orcid API version orcid path params
func (o *GetOrcidAPIVersionOrcidPathParams) WithOrcid(orcid string) *GetOrcidAPIVersionOrcidPathParams {
	o.SetOrcid(orcid)
	return o
}

// SetOrcid adds the orcid to the get orcid API version orcid path params
func (o *GetOrcidAPIVersionOrcidPathParams) SetOrcid(orcid string) {
	o.Orcid = orcid
}

// WithPath adds the path to the get orcid API version orcid path params
func (o *GetOrcidAPIVersionOrcidPathParams) WithPath(path string) *GetOrcidAPIVersionOrcidPathParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the get orcid API version orcid path params
func (o *GetOrcidAPIVersionOrcidPathParams) SetPath(path string) {
	o.Path = path
}

// WithVersion adds the version to the get orcid API version orcid path params
func (o *GetOrcidAPIVersionOrcidPathParams) WithVersion(version string) *GetOrcidAPIVersionOrcidPathParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get orcid API version orcid path params
func (o *GetOrcidAPIVersionOrcidPathParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrcidAPIVersionOrcidPathParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orcid
	if err := r.SetPathParam("orcid", o.Orcid); err != nil {
		return err
	}

	// path param path
	if err := r.SetPathParam("path", o.Path); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
