// Code generated by go-swagger; DO NOT EDIT.

package orcid_proxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutOrcidAPIVersionOrcidPathParams creates a new PutOrcidAPIVersionOrcidPathParams object
// with the default values initialized.
func NewPutOrcidAPIVersionOrcidPathParams() *PutOrcidAPIVersionOrcidPathParams {
	var ()
	return &PutOrcidAPIVersionOrcidPathParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutOrcidAPIVersionOrcidPathParamsWithTimeout creates a new PutOrcidAPIVersionOrcidPathParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutOrcidAPIVersionOrcidPathParamsWithTimeout(timeout time.Duration) *PutOrcidAPIVersionOrcidPathParams {
	var ()
	return &PutOrcidAPIVersionOrcidPathParams{

		timeout: timeout,
	}
}

// NewPutOrcidAPIVersionOrcidPathParamsWithContext creates a new PutOrcidAPIVersionOrcidPathParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutOrcidAPIVersionOrcidPathParamsWithContext(ctx context.Context) *PutOrcidAPIVersionOrcidPathParams {
	var ()
	return &PutOrcidAPIVersionOrcidPathParams{

		Context: ctx,
	}
}

// NewPutOrcidAPIVersionOrcidPathParamsWithHTTPClient creates a new PutOrcidAPIVersionOrcidPathParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutOrcidAPIVersionOrcidPathParamsWithHTTPClient(client *http.Client) *PutOrcidAPIVersionOrcidPathParams {
	var ()
	return &PutOrcidAPIVersionOrcidPathParams{
		HTTPClient: client,
	}
}

/*PutOrcidAPIVersionOrcidPathParams contains all the parameters to send to the API endpoint
for the put orcid API version orcid path operation typically these are written to a http.Request
*/
type PutOrcidAPIVersionOrcidPathParams struct {

	/*Body*/
	Body interface{}
	/*Orcid
	  User ORCID ID.

	*/
	Orcid string
	/*Path
	  The rest of the ORCID API entry point URL.

	*/
	Path string
	/*Version
	  ORCID API version

	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) WithTimeout(timeout time.Duration) *PutOrcidAPIVersionOrcidPathParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) WithContext(ctx context.Context) *PutOrcidAPIVersionOrcidPathParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) WithHTTPClient(client *http.Client) *PutOrcidAPIVersionOrcidPathParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) WithBody(body interface{}) *PutOrcidAPIVersionOrcidPathParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) SetBody(body interface{}) {
	o.Body = body
}

// WithOrcid adds the orcid to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) WithOrcid(orcid string) *PutOrcidAPIVersionOrcidPathParams {
	o.SetOrcid(orcid)
	return o
}

// SetOrcid adds the orcid to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) SetOrcid(orcid string) {
	o.Orcid = orcid
}

// WithPath adds the path to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) WithPath(path string) *PutOrcidAPIVersionOrcidPathParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) SetPath(path string) {
	o.Path = path
}

// WithVersion adds the version to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) WithVersion(version string) *PutOrcidAPIVersionOrcidPathParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the put orcid API version orcid path params
func (o *PutOrcidAPIVersionOrcidPathParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *PutOrcidAPIVersionOrcidPathParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param orcid
	if err := r.SetPathParam("orcid", o.Orcid); err != nil {
		return err
	}

	// path param path
	if err := r.SetPathParam("path", o.Path); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
