// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHangleOKCode is the HTTP code returned for type GetHangleOK
const GetHangleOKCode int = 200

/*GetHangleOK OK

swagger:response getHangleOK
*/
type GetHangleOK struct {
}

// NewGetHangleOK creates GetHangleOK with default headers values
func NewGetHangleOK() *GetHangleOK {

	return &GetHangleOK{}
}

// WriteResponse to the client
func (o *GetHangleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
