// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostHangleCreatedCode is the HTTP code returned for type PostHangleCreated
const PostHangleCreatedCode int = 201

/*PostHangleCreated OK

swagger:response postHangleCreated
*/
type PostHangleCreated struct {
}

// NewPostHangleCreated creates PostHangleCreated with default headers values
func NewPostHangleCreated() *PostHangleCreated {

	return &PostHangleCreated{}
}

// WriteResponse to the client
func (o *PostHangleCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}
