// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi UOA to ORCIDHUB
This is an example of using OAuth2 Implicit Flow in a specification to describe security to your API.


    Schemes:
      https
    Host: virtserver.swaggerhub.com
    BasePath: /uoa-orcidhub/v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
