// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi UoA to ORCIDHub
This is UoA to ORCIDHub integration application.


    Schemes:
      http
    Host: virtserver.swaggerhub.com
    BasePath: /api/v1
    Version: v1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
