// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is UoA to ORCIDHub integration application.",
    "title": "UoA to ORCIDHub",
    "version": "v1"
  },
  "host": "virtserver.swaggerhub.com",
  "basePath": "/api/v1",
  "paths": {
    "/handle": {
      "post": {
        "description": "Handle employer update event.",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "update"
        ],
        "summary": "Handle employer update event",
        "parameters": [
          {
            "description": "Message body with AUID.",
            "name": "body",
            "in": "body",
            "schema": {
              "required": [
                "subject"
              ],
              "properties": {
                "subject": {
                  "description": "User UAID",
                  "type": "string",
                  "format": "[0-9]{8,10}"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK"
          }
        }
      }
    },
    "/ping": {
      "get": {
        "security": [],
        "description": "This operation shows how to override the global security defined above, as we want to open it up for all users.",
        "summary": "Server heartbeat operation",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "implicit": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "http://example.com/oauth/auth",
      "scopes": {
        "read": "allows reading resources",
        "write": "allows modifying resources"
      }
    }
  },
  "security": [
    {
      "implicit": [
        "read",
        "write"
      ]
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is UoA to ORCIDHub integration application.",
    "title": "UoA to ORCIDHub",
    "version": "v1"
  },
  "host": "virtserver.swaggerhub.com",
  "basePath": "/api/v1",
  "paths": {
    "/handle": {
      "post": {
        "description": "Handle employer update event.",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "update"
        ],
        "summary": "Handle employer update event",
        "parameters": [
          {
            "description": "Message body with AUID.",
            "name": "body",
            "in": "body",
            "schema": {
              "required": [
                "subject"
              ],
              "properties": {
                "subject": {
                  "description": "User UAID",
                  "type": "string",
                  "format": "[0-9]{8,10}"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK"
          }
        }
      }
    },
    "/ping": {
      "get": {
        "security": [],
        "description": "This operation shows how to override the global security defined above, as we want to open it up for all users.",
        "summary": "Server heartbeat operation",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "implicit": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "http://example.com/oauth/auth",
      "scopes": {
        "read": "allows reading resources",
        "write": "allows modifying resources"
      }
    }
  },
  "security": [
    {
      "implicit": [
        "read",
        "write"
      ]
    }
  ]
}`))
}
