// Code generated by go-swagger; DO NOT EDIT.

package funds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAPIV10FundsTaskIDParams creates a new DeleteAPIV10FundsTaskIDParams object
// with the default values initialized.
func NewDeleteAPIV10FundsTaskIDParams() *DeleteAPIV10FundsTaskIDParams {
	var ()
	return &DeleteAPIV10FundsTaskIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV10FundsTaskIDParamsWithTimeout creates a new DeleteAPIV10FundsTaskIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPIV10FundsTaskIDParamsWithTimeout(timeout time.Duration) *DeleteAPIV10FundsTaskIDParams {
	var ()
	return &DeleteAPIV10FundsTaskIDParams{

		timeout: timeout,
	}
}

// NewDeleteAPIV10FundsTaskIDParamsWithContext creates a new DeleteAPIV10FundsTaskIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPIV10FundsTaskIDParamsWithContext(ctx context.Context) *DeleteAPIV10FundsTaskIDParams {
	var ()
	return &DeleteAPIV10FundsTaskIDParams{

		Context: ctx,
	}
}

// NewDeleteAPIV10FundsTaskIDParamsWithHTTPClient creates a new DeleteAPIV10FundsTaskIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPIV10FundsTaskIDParamsWithHTTPClient(client *http.Client) *DeleteAPIV10FundsTaskIDParams {
	var ()
	return &DeleteAPIV10FundsTaskIDParams{
		HTTPClient: client,
	}
}

/*DeleteAPIV10FundsTaskIDParams contains all the parameters to send to the API endpoint
for the delete API v10 funds task ID operation typically these are written to a http.Request
*/
type DeleteAPIV10FundsTaskIDParams struct {

	/*TaskID
	  Fund task ID.

	*/
	TaskID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete API v10 funds task ID params
func (o *DeleteAPIV10FundsTaskIDParams) WithTimeout(timeout time.Duration) *DeleteAPIV10FundsTaskIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v10 funds task ID params
func (o *DeleteAPIV10FundsTaskIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v10 funds task ID params
func (o *DeleteAPIV10FundsTaskIDParams) WithContext(ctx context.Context) *DeleteAPIV10FundsTaskIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v10 funds task ID params
func (o *DeleteAPIV10FundsTaskIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v10 funds task ID params
func (o *DeleteAPIV10FundsTaskIDParams) WithHTTPClient(client *http.Client) *DeleteAPIV10FundsTaskIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v10 funds task ID params
func (o *DeleteAPIV10FundsTaskIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskID adds the taskID to the delete API v10 funds task ID params
func (o *DeleteAPIV10FundsTaskIDParams) WithTaskID(taskID int64) *DeleteAPIV10FundsTaskIDParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the delete API v10 funds task ID params
func (o *DeleteAPIV10FundsTaskIDParams) SetTaskID(taskID int64) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV10FundsTaskIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param task_id
	if err := r.SetPathParam("task_id", swag.FormatInt64(o.TaskID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
