// Code generated by go-swagger; DO NOT EDIT.

package funds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIV10FundsTaskIDParams creates a new GetAPIV10FundsTaskIDParams object
// with the default values initialized.
func NewGetAPIV10FundsTaskIDParams() *GetAPIV10FundsTaskIDParams {
	var ()
	return &GetAPIV10FundsTaskIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV10FundsTaskIDParamsWithTimeout creates a new GetAPIV10FundsTaskIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV10FundsTaskIDParamsWithTimeout(timeout time.Duration) *GetAPIV10FundsTaskIDParams {
	var ()
	return &GetAPIV10FundsTaskIDParams{

		timeout: timeout,
	}
}

// NewGetAPIV10FundsTaskIDParamsWithContext creates a new GetAPIV10FundsTaskIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV10FundsTaskIDParamsWithContext(ctx context.Context) *GetAPIV10FundsTaskIDParams {
	var ()
	return &GetAPIV10FundsTaskIDParams{

		Context: ctx,
	}
}

// NewGetAPIV10FundsTaskIDParamsWithHTTPClient creates a new GetAPIV10FundsTaskIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV10FundsTaskIDParamsWithHTTPClient(client *http.Client) *GetAPIV10FundsTaskIDParams {
	var ()
	return &GetAPIV10FundsTaskIDParams{
		HTTPClient: client,
	}
}

/*GetAPIV10FundsTaskIDParams contains all the parameters to send to the API endpoint
for the get API v10 funds task ID operation typically these are written to a http.Request
*/
type GetAPIV10FundsTaskIDParams struct {

	/*TaskID
	  Fund task ID.

	*/
	TaskID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v10 funds task ID params
func (o *GetAPIV10FundsTaskIDParams) WithTimeout(timeout time.Duration) *GetAPIV10FundsTaskIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v10 funds task ID params
func (o *GetAPIV10FundsTaskIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v10 funds task ID params
func (o *GetAPIV10FundsTaskIDParams) WithContext(ctx context.Context) *GetAPIV10FundsTaskIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v10 funds task ID params
func (o *GetAPIV10FundsTaskIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v10 funds task ID params
func (o *GetAPIV10FundsTaskIDParams) WithHTTPClient(client *http.Client) *GetAPIV10FundsTaskIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v10 funds task ID params
func (o *GetAPIV10FundsTaskIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskID adds the taskID to the get API v10 funds task ID params
func (o *GetAPIV10FundsTaskIDParams) WithTaskID(taskID int64) *GetAPIV10FundsTaskIDParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get API v10 funds task ID params
func (o *GetAPIV10FundsTaskIDParams) SetTaskID(taskID int64) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV10FundsTaskIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param task_id
	if err := r.SetPathParam("task_id", swag.FormatInt64(o.TaskID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
