// Code generated by go-swagger; DO NOT EDIT.

package funds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// NewPostAPIV10FundsParams creates a new PostAPIV10FundsParams object
// with the default values initialized.
func NewPostAPIV10FundsParams() *PostAPIV10FundsParams {
	var ()
	return &PostAPIV10FundsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV10FundsParamsWithTimeout creates a new PostAPIV10FundsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV10FundsParamsWithTimeout(timeout time.Duration) *PostAPIV10FundsParams {
	var ()
	return &PostAPIV10FundsParams{

		timeout: timeout,
	}
}

// NewPostAPIV10FundsParamsWithContext creates a new PostAPIV10FundsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV10FundsParamsWithContext(ctx context.Context) *PostAPIV10FundsParams {
	var ()
	return &PostAPIV10FundsParams{

		Context: ctx,
	}
}

// NewPostAPIV10FundsParamsWithHTTPClient creates a new PostAPIV10FundsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV10FundsParamsWithHTTPClient(client *http.Client) *PostAPIV10FundsParams {
	var ()
	return &PostAPIV10FundsParams{
		HTTPClient: client,
	}
}

/*PostAPIV10FundsParams contains all the parameters to send to the API endpoint
for the post API v10 funds operation typically these are written to a http.Request
*/
type PostAPIV10FundsParams struct {

	/*Body
	  Fund task.

	*/
	Body *models.FundTask
	/*Filename
	  The batch process filename.

	*/
	Filename *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API v10 funds params
func (o *PostAPIV10FundsParams) WithTimeout(timeout time.Duration) *PostAPIV10FundsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v10 funds params
func (o *PostAPIV10FundsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v10 funds params
func (o *PostAPIV10FundsParams) WithContext(ctx context.Context) *PostAPIV10FundsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v10 funds params
func (o *PostAPIV10FundsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v10 funds params
func (o *PostAPIV10FundsParams) WithHTTPClient(client *http.Client) *PostAPIV10FundsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v10 funds params
func (o *PostAPIV10FundsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API v10 funds params
func (o *PostAPIV10FundsParams) WithBody(body *models.FundTask) *PostAPIV10FundsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API v10 funds params
func (o *PostAPIV10FundsParams) SetBody(body *models.FundTask) {
	o.Body = body
}

// WithFilename adds the filename to the post API v10 funds params
func (o *PostAPIV10FundsParams) WithFilename(filename *string) *PostAPIV10FundsParams {
	o.SetFilename(filename)
	return o
}

// SetFilename adds the filename to the post API v10 funds params
func (o *PostAPIV10FundsParams) SetFilename(filename *string) {
	o.Filename = filename
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV10FundsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Filename != nil {

		// query param filename
		var qrFilename string
		if o.Filename != nil {
			qrFilename = *o.Filename
		}
		qFilename := qrFilename
		if qFilename != "" {
			if err := r.SetQueryParam("filename", qFilename); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
