// Code generated by go-swagger; DO NOT EDIT.

package funds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// PostAPIV10FundsTaskIDReader is a Reader for the PostAPIV10FundsTaskID structure.
type PostAPIV10FundsTaskIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV10FundsTaskIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAPIV10FundsTaskIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostAPIV10FundsTaskIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostAPIV10FundsTaskIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostAPIV10FundsTaskIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAPIV10FundsTaskIDOK creates a PostAPIV10FundsTaskIDOK with default headers values
func NewPostAPIV10FundsTaskIDOK() *PostAPIV10FundsTaskIDOK {
	return &PostAPIV10FundsTaskIDOK{}
}

/*PostAPIV10FundsTaskIDOK handles this case with default header values.

successful operation
*/
type PostAPIV10FundsTaskIDOK struct {
	Payload *models.FundTask
}

func (o *PostAPIV10FundsTaskIDOK) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/funds/{task_id}][%d] postApiV10FundsTaskIdOK  %+v", 200, o.Payload)
}

func (o *PostAPIV10FundsTaskIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FundTask)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10FundsTaskIDUnauthorized creates a PostAPIV10FundsTaskIDUnauthorized with default headers values
func NewPostAPIV10FundsTaskIDUnauthorized() *PostAPIV10FundsTaskIDUnauthorized {
	return &PostAPIV10FundsTaskIDUnauthorized{}
}

/*PostAPIV10FundsTaskIDUnauthorized handles this case with default header values.

Unauthorized
*/
type PostAPIV10FundsTaskIDUnauthorized struct {
	Payload *models.Error
}

func (o *PostAPIV10FundsTaskIDUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/funds/{task_id}][%d] postApiV10FundsTaskIdUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAPIV10FundsTaskIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10FundsTaskIDForbidden creates a PostAPIV10FundsTaskIDForbidden with default headers values
func NewPostAPIV10FundsTaskIDForbidden() *PostAPIV10FundsTaskIDForbidden {
	return &PostAPIV10FundsTaskIDForbidden{}
}

/*PostAPIV10FundsTaskIDForbidden handles this case with default header values.

Access Denied
*/
type PostAPIV10FundsTaskIDForbidden struct {
	Payload *models.Error
}

func (o *PostAPIV10FundsTaskIDForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/funds/{task_id}][%d] postApiV10FundsTaskIdForbidden  %+v", 403, o.Payload)
}

func (o *PostAPIV10FundsTaskIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10FundsTaskIDNotFound creates a PostAPIV10FundsTaskIDNotFound with default headers values
func NewPostAPIV10FundsTaskIDNotFound() *PostAPIV10FundsTaskIDNotFound {
	return &PostAPIV10FundsTaskIDNotFound{}
}

/*PostAPIV10FundsTaskIDNotFound handles this case with default header values.

The specified resource was not found
*/
type PostAPIV10FundsTaskIDNotFound struct {
	Payload *models.Error
}

func (o *PostAPIV10FundsTaskIDNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/funds/{task_id}][%d] postApiV10FundsTaskIdNotFound  %+v", 404, o.Payload)
}

func (o *PostAPIV10FundsTaskIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
