// Code generated by go-swagger; DO NOT EDIT.

package funds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// PostAPIV10FundsReader is a Reader for the PostAPIV10Funds structure.
type PostAPIV10FundsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV10FundsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAPIV10FundsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostAPIV10FundsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostAPIV10FundsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostAPIV10FundsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAPIV10FundsOK creates a PostAPIV10FundsOK with default headers values
func NewPostAPIV10FundsOK() *PostAPIV10FundsOK {
	return &PostAPIV10FundsOK{}
}

/*PostAPIV10FundsOK handles this case with default header values.

successful operation
*/
type PostAPIV10FundsOK struct {
	Payload *models.FundTask
}

func (o *PostAPIV10FundsOK) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/funds][%d] postApiV10FundsOK  %+v", 200, o.Payload)
}

func (o *PostAPIV10FundsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FundTask)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10FundsUnauthorized creates a PostAPIV10FundsUnauthorized with default headers values
func NewPostAPIV10FundsUnauthorized() *PostAPIV10FundsUnauthorized {
	return &PostAPIV10FundsUnauthorized{}
}

/*PostAPIV10FundsUnauthorized handles this case with default header values.

Unauthorized
*/
type PostAPIV10FundsUnauthorized struct {
	Payload *models.Error
}

func (o *PostAPIV10FundsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/funds][%d] postApiV10FundsUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAPIV10FundsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10FundsForbidden creates a PostAPIV10FundsForbidden with default headers values
func NewPostAPIV10FundsForbidden() *PostAPIV10FundsForbidden {
	return &PostAPIV10FundsForbidden{}
}

/*PostAPIV10FundsForbidden handles this case with default header values.

Access Denied
*/
type PostAPIV10FundsForbidden struct {
	Payload *models.Error
}

func (o *PostAPIV10FundsForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/funds][%d] postApiV10FundsForbidden  %+v", 403, o.Payload)
}

func (o *PostAPIV10FundsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10FundsNotFound creates a PostAPIV10FundsNotFound with default headers values
func NewPostAPIV10FundsNotFound() *PostAPIV10FundsNotFound {
	return &PostAPIV10FundsNotFound{}
}

/*PostAPIV10FundsNotFound handles this case with default header values.

The specified resource was not found
*/
type PostAPIV10FundsNotFound struct {
	Payload *models.Error
}

func (o *PostAPIV10FundsNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/funds][%d] postApiV10FundsNotFound  %+v", 404, o.Payload)
}

func (o *PostAPIV10FundsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
