// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIV10UsersIdentifierParams creates a new GetAPIV10UsersIdentifierParams object
// with the default values initialized.
func NewGetAPIV10UsersIdentifierParams() *GetAPIV10UsersIdentifierParams {
	var ()
	return &GetAPIV10UsersIdentifierParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV10UsersIdentifierParamsWithTimeout creates a new GetAPIV10UsersIdentifierParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV10UsersIdentifierParamsWithTimeout(timeout time.Duration) *GetAPIV10UsersIdentifierParams {
	var ()
	return &GetAPIV10UsersIdentifierParams{

		timeout: timeout,
	}
}

// NewGetAPIV10UsersIdentifierParamsWithContext creates a new GetAPIV10UsersIdentifierParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV10UsersIdentifierParamsWithContext(ctx context.Context) *GetAPIV10UsersIdentifierParams {
	var ()
	return &GetAPIV10UsersIdentifierParams{

		Context: ctx,
	}
}

// NewGetAPIV10UsersIdentifierParamsWithHTTPClient creates a new GetAPIV10UsersIdentifierParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV10UsersIdentifierParamsWithHTTPClient(client *http.Client) *GetAPIV10UsersIdentifierParams {
	var ()
	return &GetAPIV10UsersIdentifierParams{
		HTTPClient: client,
	}
}

/*GetAPIV10UsersIdentifierParams contains all the parameters to send to the API endpoint
for the get API v10 users identifier operation typically these are written to a http.Request
*/
type GetAPIV10UsersIdentifierParams struct {

	/*Identifier
	  The unique identifier (email, ORCID iD, or eppn)

	*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v10 users identifier params
func (o *GetAPIV10UsersIdentifierParams) WithTimeout(timeout time.Duration) *GetAPIV10UsersIdentifierParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v10 users identifier params
func (o *GetAPIV10UsersIdentifierParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v10 users identifier params
func (o *GetAPIV10UsersIdentifierParams) WithContext(ctx context.Context) *GetAPIV10UsersIdentifierParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v10 users identifier params
func (o *GetAPIV10UsersIdentifierParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v10 users identifier params
func (o *GetAPIV10UsersIdentifierParams) WithHTTPClient(client *http.Client) *GetAPIV10UsersIdentifierParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v10 users identifier params
func (o *GetAPIV10UsersIdentifierParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIdentifier adds the identifier to the get API v10 users identifier params
func (o *GetAPIV10UsersIdentifierParams) WithIdentifier(identifier string) *GetAPIV10UsersIdentifierParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the get API v10 users identifier params
func (o *GetAPIV10UsersIdentifierParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV10UsersIdentifierParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
