// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// GetAPIV10UsersReader is a Reader for the GetAPIV10Users structure.
type GetAPIV10UsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV10UsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV10UsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetAPIV10UsersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAPIV10UsersForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetAPIV10UsersNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewGetAPIV10UsersUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV10UsersOK creates a GetAPIV10UsersOK with default headers values
func NewGetAPIV10UsersOK() *GetAPIV10UsersOK {
	return &GetAPIV10UsersOK{}
}

/*GetAPIV10UsersOK handles this case with default header values.

successful operation
*/
type GetAPIV10UsersOK struct {
	Payload models.UserListAPIResponse
}

func (o *GetAPIV10UsersOK) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/users][%d] getApiV10UsersOK  %+v", 200, o.Payload)
}

func (o *GetAPIV10UsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV10UsersUnauthorized creates a GetAPIV10UsersUnauthorized with default headers values
func NewGetAPIV10UsersUnauthorized() *GetAPIV10UsersUnauthorized {
	return &GetAPIV10UsersUnauthorized{}
}

/*GetAPIV10UsersUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAPIV10UsersUnauthorized struct {
	Payload *models.Error
}

func (o *GetAPIV10UsersUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/users][%d] getApiV10UsersUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAPIV10UsersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV10UsersForbidden creates a GetAPIV10UsersForbidden with default headers values
func NewGetAPIV10UsersForbidden() *GetAPIV10UsersForbidden {
	return &GetAPIV10UsersForbidden{}
}

/*GetAPIV10UsersForbidden handles this case with default header values.

Access Denied
*/
type GetAPIV10UsersForbidden struct {
	Payload *models.Error
}

func (o *GetAPIV10UsersForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/users][%d] getApiV10UsersForbidden  %+v", 403, o.Payload)
}

func (o *GetAPIV10UsersForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV10UsersNotFound creates a GetAPIV10UsersNotFound with default headers values
func NewGetAPIV10UsersNotFound() *GetAPIV10UsersNotFound {
	return &GetAPIV10UsersNotFound{}
}

/*GetAPIV10UsersNotFound handles this case with default header values.

The specified resource was not found
*/
type GetAPIV10UsersNotFound struct {
	Payload *models.Error
}

func (o *GetAPIV10UsersNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/users][%d] getApiV10UsersNotFound  %+v", 404, o.Payload)
}

func (o *GetAPIV10UsersNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV10UsersUnprocessableEntity creates a GetAPIV10UsersUnprocessableEntity with default headers values
func NewGetAPIV10UsersUnprocessableEntity() *GetAPIV10UsersUnprocessableEntity {
	return &GetAPIV10UsersUnprocessableEntity{}
}

/*GetAPIV10UsersUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type GetAPIV10UsersUnprocessableEntity struct {
}

func (o *GetAPIV10UsersUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/users][%d] getApiV10UsersUnprocessableEntity ", 422)
}

func (o *GetAPIV10UsersUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
