// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// GetAPIV10UsersIdentifierReader is a Reader for the GetAPIV10UsersIdentifier structure.
type GetAPIV10UsersIdentifierReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV10UsersIdentifierReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV10UsersIdentifierOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAPIV10UsersIdentifierBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetAPIV10UsersIdentifierNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV10UsersIdentifierOK creates a GetAPIV10UsersIdentifierOK with default headers values
func NewGetAPIV10UsersIdentifierOK() *GetAPIV10UsersIdentifierOK {
	return &GetAPIV10UsersIdentifierOK{}
}

/*GetAPIV10UsersIdentifierOK handles this case with default header values.

successful operation
*/
type GetAPIV10UsersIdentifierOK struct {
	Payload *models.HubUser
}

func (o *GetAPIV10UsersIdentifierOK) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/users/{identifier}][%d] getApiV10UsersIdentifierOK  %+v", 200, o.Payload)
}

func (o *GetAPIV10UsersIdentifierOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HubUser)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV10UsersIdentifierBadRequest creates a GetAPIV10UsersIdentifierBadRequest with default headers values
func NewGetAPIV10UsersIdentifierBadRequest() *GetAPIV10UsersIdentifierBadRequest {
	return &GetAPIV10UsersIdentifierBadRequest{}
}

/*GetAPIV10UsersIdentifierBadRequest handles this case with default header values.

Invalid identifier supplied
*/
type GetAPIV10UsersIdentifierBadRequest struct {
}

func (o *GetAPIV10UsersIdentifierBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/users/{identifier}][%d] getApiV10UsersIdentifierBadRequest ", 400)
}

func (o *GetAPIV10UsersIdentifierBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIV10UsersIdentifierNotFound creates a GetAPIV10UsersIdentifierNotFound with default headers values
func NewGetAPIV10UsersIdentifierNotFound() *GetAPIV10UsersIdentifierNotFound {
	return &GetAPIV10UsersIdentifierNotFound{}
}

/*GetAPIV10UsersIdentifierNotFound handles this case with default header values.

User not found
*/
type GetAPIV10UsersIdentifierNotFound struct {
}

func (o *GetAPIV10UsersIdentifierNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/users/{identifier}][%d] getApiV10UsersIdentifierNotFound ", 404)
}

func (o *GetAPIV10UsersIdentifierNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
