// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new users API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for users API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetAPIV10Users returns the list of the user belonging to the organisation
*/
func (a *Client) GetAPIV10Users(params *GetAPIV10UsersParams, authInfo runtime.ClientAuthInfoWriter) (*GetAPIV10UsersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIV10UsersParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetAPIV10Users",
		Method:             "GET",
		PathPattern:        "/api/v1.0/users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetAPIV10UsersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetAPIV10UsersOK), nil

}

/*
GetAPIV10UsersIdentifier verifies if a user with given email address or o r c ID ID exists
*/
func (a *Client) GetAPIV10UsersIdentifier(params *GetAPIV10UsersIdentifierParams, authInfo runtime.ClientAuthInfoWriter) (*GetAPIV10UsersIdentifierOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIV10UsersIdentifierParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetAPIV10UsersIdentifier",
		Method:             "GET",
		PathPattern:        "/api/v1.0/users/{identifier}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetAPIV10UsersIdentifierReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetAPIV10UsersIdentifierOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
