// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// GetCodesEmployeeActionReader is a Reader for the GetCodesEmployeeAction structure.
type GetCodesEmployeeActionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCodesEmployeeActionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCodesEmployeeActionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetCodesEmployeeActionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetCodesEmployeeActionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCodesEmployeeActionOK creates a GetCodesEmployeeActionOK with default headers values
func NewGetCodesEmployeeActionOK() *GetCodesEmployeeActionOK {
	return &GetCodesEmployeeActionOK{}
}

/*GetCodesEmployeeActionOK handles this case with default header values.

User information
*/
type GetCodesEmployeeActionOK struct {
	Payload models.Code
}

func (o *GetCodesEmployeeActionOK) Error() string {
	return fmt.Sprintf("[GET /codes/employee-action][%d] getCodesEmployeeActionOK  %+v", 200, o.Payload)
}

func (o *GetCodesEmployeeActionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCodesEmployeeActionUnauthorized creates a GetCodesEmployeeActionUnauthorized with default headers values
func NewGetCodesEmployeeActionUnauthorized() *GetCodesEmployeeActionUnauthorized {
	return &GetCodesEmployeeActionUnauthorized{}
}

/*GetCodesEmployeeActionUnauthorized handles this case with default header values.

Unauthorized
*/
type GetCodesEmployeeActionUnauthorized struct {
}

func (o *GetCodesEmployeeActionUnauthorized) Error() string {
	return fmt.Sprintf("[GET /codes/employee-action][%d] getCodesEmployeeActionUnauthorized ", 401)
}

func (o *GetCodesEmployeeActionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetCodesEmployeeActionInternalServerError creates a GetCodesEmployeeActionInternalServerError with default headers values
func NewGetCodesEmployeeActionInternalServerError() *GetCodesEmployeeActionInternalServerError {
	return &GetCodesEmployeeActionInternalServerError{}
}

/*GetCodesEmployeeActionInternalServerError handles this case with default header values.

Unexpected error
*/
type GetCodesEmployeeActionInternalServerError struct {
}

func (o *GetCodesEmployeeActionInternalServerError) Error() string {
	return fmt.Sprintf("[GET /codes/employee-action][%d] getCodesEmployeeActionInternalServerError ", 500)
}

func (o *GetCodesEmployeeActionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
