// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCodesStatusParams creates a new GetCodesStatusParams object
// with the default values initialized.
func NewGetCodesStatusParams() *GetCodesStatusParams {

	return &GetCodesStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCodesStatusParamsWithTimeout creates a new GetCodesStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCodesStatusParamsWithTimeout(timeout time.Duration) *GetCodesStatusParams {

	return &GetCodesStatusParams{

		timeout: timeout,
	}
}

// NewGetCodesStatusParamsWithContext creates a new GetCodesStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCodesStatusParamsWithContext(ctx context.Context) *GetCodesStatusParams {

	return &GetCodesStatusParams{

		Context: ctx,
	}
}

// NewGetCodesStatusParamsWithHTTPClient creates a new GetCodesStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCodesStatusParamsWithHTTPClient(client *http.Client) *GetCodesStatusParams {

	return &GetCodesStatusParams{
		HTTPClient: client,
	}
}

/*GetCodesStatusParams contains all the parameters to send to the API endpoint
for the get codes status operation typically these are written to a http.Request
*/
type GetCodesStatusParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get codes status params
func (o *GetCodesStatusParams) WithTimeout(timeout time.Duration) *GetCodesStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get codes status params
func (o *GetCodesStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get codes status params
func (o *GetCodesStatusParams) WithContext(ctx context.Context) *GetCodesStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get codes status params
func (o *GetCodesStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get codes status params
func (o *GetCodesStatusParams) WithHTTPClient(client *http.Client) *GetCodesStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get codes status params
func (o *GetCodesStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCodesStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
