// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCodesRegtempParams creates a new GetCodesRegtempParams object
// with the default values initialized.
func NewGetCodesRegtempParams() *GetCodesRegtempParams {

	return &GetCodesRegtempParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCodesRegtempParamsWithTimeout creates a new GetCodesRegtempParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCodesRegtempParamsWithTimeout(timeout time.Duration) *GetCodesRegtempParams {

	return &GetCodesRegtempParams{

		timeout: timeout,
	}
}

// NewGetCodesRegtempParamsWithContext creates a new GetCodesRegtempParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCodesRegtempParamsWithContext(ctx context.Context) *GetCodesRegtempParams {

	return &GetCodesRegtempParams{

		Context: ctx,
	}
}

// NewGetCodesRegtempParamsWithHTTPClient creates a new GetCodesRegtempParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCodesRegtempParamsWithHTTPClient(client *http.Client) *GetCodesRegtempParams {

	return &GetCodesRegtempParams{
		HTTPClient: client,
	}
}

/*GetCodesRegtempParams contains all the parameters to send to the API endpoint
for the get codes regtemp operation typically these are written to a http.Request
*/
type GetCodesRegtempParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get codes regtemp params
func (o *GetCodesRegtempParams) WithTimeout(timeout time.Duration) *GetCodesRegtempParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get codes regtemp params
func (o *GetCodesRegtempParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get codes regtemp params
func (o *GetCodesRegtempParams) WithContext(ctx context.Context) *GetCodesRegtempParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get codes regtemp params
func (o *GetCodesRegtempParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get codes regtemp params
func (o *GetCodesRegtempParams) WithHTTPClient(client *http.Client) *GetCodesRegtempParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get codes regtemp params
func (o *GetCodesRegtempParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCodesRegtempParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
