// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// GetCodesStatusReader is a Reader for the GetCodesStatus structure.
type GetCodesStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCodesStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCodesStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetCodesStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetCodesStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCodesStatusOK creates a GetCodesStatusOK with default headers values
func NewGetCodesStatusOK() *GetCodesStatusOK {
	return &GetCodesStatusOK{}
}

/*GetCodesStatusOK handles this case with default header values.

User information
*/
type GetCodesStatusOK struct {
	Payload models.Code
}

func (o *GetCodesStatusOK) Error() string {
	return fmt.Sprintf("[GET /codes/status][%d] getCodesStatusOK  %+v", 200, o.Payload)
}

func (o *GetCodesStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCodesStatusUnauthorized creates a GetCodesStatusUnauthorized with default headers values
func NewGetCodesStatusUnauthorized() *GetCodesStatusUnauthorized {
	return &GetCodesStatusUnauthorized{}
}

/*GetCodesStatusUnauthorized handles this case with default header values.

Unauthorized
*/
type GetCodesStatusUnauthorized struct {
}

func (o *GetCodesStatusUnauthorized) Error() string {
	return fmt.Sprintf("[GET /codes/status][%d] getCodesStatusUnauthorized ", 401)
}

func (o *GetCodesStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetCodesStatusInternalServerError creates a GetCodesStatusInternalServerError with default headers values
func NewGetCodesStatusInternalServerError() *GetCodesStatusInternalServerError {
	return &GetCodesStatusInternalServerError{}
}

/*GetCodesStatusInternalServerError handles this case with default header values.

Unexpected error
*/
type GetCodesStatusInternalServerError struct {
}

func (o *GetCodesStatusInternalServerError) Error() string {
	return fmt.Sprintf("[GET /codes/status][%d] getCodesStatusInternalServerError ", 500)
}

func (o *GetCodesStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
