// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// GetCodesRegtempReader is a Reader for the GetCodesRegtemp structure.
type GetCodesRegtempReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCodesRegtempReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCodesRegtempOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetCodesRegtempUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetCodesRegtempInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCodesRegtempOK creates a GetCodesRegtempOK with default headers values
func NewGetCodesRegtempOK() *GetCodesRegtempOK {
	return &GetCodesRegtempOK{}
}

/*GetCodesRegtempOK handles this case with default header values.

User information
*/
type GetCodesRegtempOK struct {
	Payload models.Code
}

func (o *GetCodesRegtempOK) Error() string {
	return fmt.Sprintf("[GET /codes/regtemp][%d] getCodesRegtempOK  %+v", 200, o.Payload)
}

func (o *GetCodesRegtempOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCodesRegtempUnauthorized creates a GetCodesRegtempUnauthorized with default headers values
func NewGetCodesRegtempUnauthorized() *GetCodesRegtempUnauthorized {
	return &GetCodesRegtempUnauthorized{}
}

/*GetCodesRegtempUnauthorized handles this case with default header values.

Unauthorized
*/
type GetCodesRegtempUnauthorized struct {
}

func (o *GetCodesRegtempUnauthorized) Error() string {
	return fmt.Sprintf("[GET /codes/regtemp][%d] getCodesRegtempUnauthorized ", 401)
}

func (o *GetCodesRegtempUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetCodesRegtempInternalServerError creates a GetCodesRegtempInternalServerError with default headers values
func NewGetCodesRegtempInternalServerError() *GetCodesRegtempInternalServerError {
	return &GetCodesRegtempInternalServerError{}
}

/*GetCodesRegtempInternalServerError handles this case with default header values.

Unexpected error
*/
type GetCodesRegtempInternalServerError struct {
}

func (o *GetCodesRegtempInternalServerError) Error() string {
	return fmt.Sprintf("[GET /codes/regtemp][%d] getCodesRegtempInternalServerError ", 500)
}

func (o *GetCodesRegtempInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
