// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// GetEmployeeSelfReader is a Reader for the GetEmployeeSelf structure.
type GetEmployeeSelfReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEmployeeSelfReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetEmployeeSelfOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetEmployeeSelfBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetEmployeeSelfUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetEmployeeSelfNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetEmployeeSelfInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 501:
		result := NewGetEmployeeSelfNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEmployeeSelfOK creates a GetEmployeeSelfOK with default headers values
func NewGetEmployeeSelfOK() *GetEmployeeSelfOK {
	return &GetEmployeeSelfOK{}
}

/*GetEmployeeSelfOK handles this case with default header values.

hremployee response
*/
type GetEmployeeSelfOK struct {
	Payload *models.Hremployee
}

func (o *GetEmployeeSelfOK) Error() string {
	return fmt.Sprintf("[GET /employee/self][%d] getEmployeeSelfOK  %+v", 200, o.Payload)
}

func (o *GetEmployeeSelfOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Hremployee)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEmployeeSelfBadRequest creates a GetEmployeeSelfBadRequest with default headers values
func NewGetEmployeeSelfBadRequest() *GetEmployeeSelfBadRequest {
	return &GetEmployeeSelfBadRequest{}
}

/*GetEmployeeSelfBadRequest handles this case with default header values.

Bad request (unsupported id)
*/
type GetEmployeeSelfBadRequest struct {
	Payload *models.Error
}

func (o *GetEmployeeSelfBadRequest) Error() string {
	return fmt.Sprintf("[GET /employee/self][%d] getEmployeeSelfBadRequest  %+v", 400, o.Payload)
}

func (o *GetEmployeeSelfBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEmployeeSelfUnauthorized creates a GetEmployeeSelfUnauthorized with default headers values
func NewGetEmployeeSelfUnauthorized() *GetEmployeeSelfUnauthorized {
	return &GetEmployeeSelfUnauthorized{}
}

/*GetEmployeeSelfUnauthorized handles this case with default header values.

Unauthorized
*/
type GetEmployeeSelfUnauthorized struct {
}

func (o *GetEmployeeSelfUnauthorized) Error() string {
	return fmt.Sprintf("[GET /employee/self][%d] getEmployeeSelfUnauthorized ", 401)
}

func (o *GetEmployeeSelfUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEmployeeSelfNotFound creates a GetEmployeeSelfNotFound with default headers values
func NewGetEmployeeSelfNotFound() *GetEmployeeSelfNotFound {
	return &GetEmployeeSelfNotFound{}
}

/*GetEmployeeSelfNotFound handles this case with default header values.

employee not found
*/
type GetEmployeeSelfNotFound struct {
}

func (o *GetEmployeeSelfNotFound) Error() string {
	return fmt.Sprintf("[GET /employee/self][%d] getEmployeeSelfNotFound ", 404)
}

func (o *GetEmployeeSelfNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEmployeeSelfInternalServerError creates a GetEmployeeSelfInternalServerError with default headers values
func NewGetEmployeeSelfInternalServerError() *GetEmployeeSelfInternalServerError {
	return &GetEmployeeSelfInternalServerError{}
}

/*GetEmployeeSelfInternalServerError handles this case with default header values.

Unexpected error
*/
type GetEmployeeSelfInternalServerError struct {
}

func (o *GetEmployeeSelfInternalServerError) Error() string {
	return fmt.Sprintf("[GET /employee/self][%d] getEmployeeSelfInternalServerError ", 500)
}

func (o *GetEmployeeSelfInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEmployeeSelfNotImplemented creates a GetEmployeeSelfNotImplemented with default headers values
func NewGetEmployeeSelfNotImplemented() *GetEmployeeSelfNotImplemented {
	return &GetEmployeeSelfNotImplemented{}
}

/*GetEmployeeSelfNotImplemented handles this case with default header values.

Unsupported operation (not implemented)
*/
type GetEmployeeSelfNotImplemented struct {
}

func (o *GetEmployeeSelfNotImplemented) Error() string {
	return fmt.Sprintf("[GET /employee/self][%d] getEmployeeSelfNotImplemented ", 501)
}

func (o *GetEmployeeSelfNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
