// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// GetCodesEmployeeStatusReader is a Reader for the GetCodesEmployeeStatus structure.
type GetCodesEmployeeStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCodesEmployeeStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCodesEmployeeStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetCodesEmployeeStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetCodesEmployeeStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCodesEmployeeStatusOK creates a GetCodesEmployeeStatusOK with default headers values
func NewGetCodesEmployeeStatusOK() *GetCodesEmployeeStatusOK {
	return &GetCodesEmployeeStatusOK{}
}

/*GetCodesEmployeeStatusOK handles this case with default header values.

User information
*/
type GetCodesEmployeeStatusOK struct {
	Payload models.Code
}

func (o *GetCodesEmployeeStatusOK) Error() string {
	return fmt.Sprintf("[GET /codes/employee-status][%d] getCodesEmployeeStatusOK  %+v", 200, o.Payload)
}

func (o *GetCodesEmployeeStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCodesEmployeeStatusUnauthorized creates a GetCodesEmployeeStatusUnauthorized with default headers values
func NewGetCodesEmployeeStatusUnauthorized() *GetCodesEmployeeStatusUnauthorized {
	return &GetCodesEmployeeStatusUnauthorized{}
}

/*GetCodesEmployeeStatusUnauthorized handles this case with default header values.

Unauthorized
*/
type GetCodesEmployeeStatusUnauthorized struct {
}

func (o *GetCodesEmployeeStatusUnauthorized) Error() string {
	return fmt.Sprintf("[GET /codes/employee-status][%d] getCodesEmployeeStatusUnauthorized ", 401)
}

func (o *GetCodesEmployeeStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetCodesEmployeeStatusInternalServerError creates a GetCodesEmployeeStatusInternalServerError with default headers values
func NewGetCodesEmployeeStatusInternalServerError() *GetCodesEmployeeStatusInternalServerError {
	return &GetCodesEmployeeStatusInternalServerError{}
}

/*GetCodesEmployeeStatusInternalServerError handles this case with default header values.

Unexpected error
*/
type GetCodesEmployeeStatusInternalServerError struct {
}

func (o *GetCodesEmployeeStatusInternalServerError) Error() string {
	return fmt.Sprintf("[GET /codes/employee-status][%d] getCodesEmployeeStatusInternalServerError ", 500)
}

func (o *GetCodesEmployeeStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
