// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEmployeeUpiOrIDParams creates a new GetEmployeeUpiOrIDParams object
// with the default values initialized.
func NewGetEmployeeUpiOrIDParams() *GetEmployeeUpiOrIDParams {
	var ()
	return &GetEmployeeUpiOrIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEmployeeUpiOrIDParamsWithTimeout creates a new GetEmployeeUpiOrIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEmployeeUpiOrIDParamsWithTimeout(timeout time.Duration) *GetEmployeeUpiOrIDParams {
	var ()
	return &GetEmployeeUpiOrIDParams{

		timeout: timeout,
	}
}

// NewGetEmployeeUpiOrIDParamsWithContext creates a new GetEmployeeUpiOrIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEmployeeUpiOrIDParamsWithContext(ctx context.Context) *GetEmployeeUpiOrIDParams {
	var ()
	return &GetEmployeeUpiOrIDParams{

		Context: ctx,
	}
}

// NewGetEmployeeUpiOrIDParamsWithHTTPClient creates a new GetEmployeeUpiOrIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEmployeeUpiOrIDParamsWithHTTPClient(client *http.Client) *GetEmployeeUpiOrIDParams {
	var ()
	return &GetEmployeeUpiOrIDParams{
		HTTPClient: client,
	}
}

/*GetEmployeeUpiOrIDParams contains all the parameters to send to the API endpoint
for the get employee upi or ID operation typically these are written to a http.Request
*/
type GetEmployeeUpiOrIDParams struct {

	/*UpiOrID
	  Upi or Id of an employee

	*/
	UpiOrID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get employee upi or ID params
func (o *GetEmployeeUpiOrIDParams) WithTimeout(timeout time.Duration) *GetEmployeeUpiOrIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get employee upi or ID params
func (o *GetEmployeeUpiOrIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get employee upi or ID params
func (o *GetEmployeeUpiOrIDParams) WithContext(ctx context.Context) *GetEmployeeUpiOrIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get employee upi or ID params
func (o *GetEmployeeUpiOrIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get employee upi or ID params
func (o *GetEmployeeUpiOrIDParams) WithHTTPClient(client *http.Client) *GetEmployeeUpiOrIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get employee upi or ID params
func (o *GetEmployeeUpiOrIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUpiOrID adds the upiOrID to the get employee upi or ID params
func (o *GetEmployeeUpiOrIDParams) WithUpiOrID(upiOrID string) *GetEmployeeUpiOrIDParams {
	o.SetUpiOrID(upiOrID)
	return o
}

// SetUpiOrID adds the upiOrId to the get employee upi or ID params
func (o *GetEmployeeUpiOrIDParams) SetUpiOrID(upiOrID string) {
	o.UpiOrID = upiOrID
}

// WriteToRequest writes these params to a swagger request
func (o *GetEmployeeUpiOrIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param upiOrId
	if err := r.SetPathParam("upiOrId", o.UpiOrID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
