// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCodesEmployeeActionParams creates a new GetCodesEmployeeActionParams object
// with the default values initialized.
func NewGetCodesEmployeeActionParams() *GetCodesEmployeeActionParams {

	return &GetCodesEmployeeActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCodesEmployeeActionParamsWithTimeout creates a new GetCodesEmployeeActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCodesEmployeeActionParamsWithTimeout(timeout time.Duration) *GetCodesEmployeeActionParams {

	return &GetCodesEmployeeActionParams{

		timeout: timeout,
	}
}

// NewGetCodesEmployeeActionParamsWithContext creates a new GetCodesEmployeeActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCodesEmployeeActionParamsWithContext(ctx context.Context) *GetCodesEmployeeActionParams {

	return &GetCodesEmployeeActionParams{

		Context: ctx,
	}
}

// NewGetCodesEmployeeActionParamsWithHTTPClient creates a new GetCodesEmployeeActionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCodesEmployeeActionParamsWithHTTPClient(client *http.Client) *GetCodesEmployeeActionParams {

	return &GetCodesEmployeeActionParams{
		HTTPClient: client,
	}
}

/*GetCodesEmployeeActionParams contains all the parameters to send to the API endpoint
for the get codes employee action operation typically these are written to a http.Request
*/
type GetCodesEmployeeActionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get codes employee action params
func (o *GetCodesEmployeeActionParams) WithTimeout(timeout time.Duration) *GetCodesEmployeeActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get codes employee action params
func (o *GetCodesEmployeeActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get codes employee action params
func (o *GetCodesEmployeeActionParams) WithContext(ctx context.Context) *GetCodesEmployeeActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get codes employee action params
func (o *GetCodesEmployeeActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get codes employee action params
func (o *GetCodesEmployeeActionParams) WithHTTPClient(client *http.Client) *GetCodesEmployeeActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get codes employee action params
func (o *GetCodesEmployeeActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCodesEmployeeActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
