// Code generated by go-swagger; DO NOT EDIT.

package peer_reviews

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// DeleteAPIV10PeerReviewsTaskIDReader is a Reader for the DeleteAPIV10PeerReviewsTaskID structure.
type DeleteAPIV10PeerReviewsTaskIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV10PeerReviewsTaskIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAPIV10PeerReviewsTaskIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteAPIV10PeerReviewsTaskIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteAPIV10PeerReviewsTaskIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteAPIV10PeerReviewsTaskIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAPIV10PeerReviewsTaskIDOK creates a DeleteAPIV10PeerReviewsTaskIDOK with default headers values
func NewDeleteAPIV10PeerReviewsTaskIDOK() *DeleteAPIV10PeerReviewsTaskIDOK {
	return &DeleteAPIV10PeerReviewsTaskIDOK{}
}

/*DeleteAPIV10PeerReviewsTaskIDOK handles this case with default header values.

Successful operation
*/
type DeleteAPIV10PeerReviewsTaskIDOK struct {
}

func (o *DeleteAPIV10PeerReviewsTaskIDOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1.0/peer-reviews/{task_id}][%d] deleteApiV10PeerReviewsTaskIdOK ", 200)
}

func (o *DeleteAPIV10PeerReviewsTaskIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV10PeerReviewsTaskIDUnauthorized creates a DeleteAPIV10PeerReviewsTaskIDUnauthorized with default headers values
func NewDeleteAPIV10PeerReviewsTaskIDUnauthorized() *DeleteAPIV10PeerReviewsTaskIDUnauthorized {
	return &DeleteAPIV10PeerReviewsTaskIDUnauthorized{}
}

/*DeleteAPIV10PeerReviewsTaskIDUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteAPIV10PeerReviewsTaskIDUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteAPIV10PeerReviewsTaskIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v1.0/peer-reviews/{task_id}][%d] deleteApiV10PeerReviewsTaskIdUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteAPIV10PeerReviewsTaskIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPIV10PeerReviewsTaskIDForbidden creates a DeleteAPIV10PeerReviewsTaskIDForbidden with default headers values
func NewDeleteAPIV10PeerReviewsTaskIDForbidden() *DeleteAPIV10PeerReviewsTaskIDForbidden {
	return &DeleteAPIV10PeerReviewsTaskIDForbidden{}
}

/*DeleteAPIV10PeerReviewsTaskIDForbidden handles this case with default header values.

Access Denied
*/
type DeleteAPIV10PeerReviewsTaskIDForbidden struct {
	Payload *models.Error
}

func (o *DeleteAPIV10PeerReviewsTaskIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v1.0/peer-reviews/{task_id}][%d] deleteApiV10PeerReviewsTaskIdForbidden  %+v", 403, o.Payload)
}

func (o *DeleteAPIV10PeerReviewsTaskIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPIV10PeerReviewsTaskIDNotFound creates a DeleteAPIV10PeerReviewsTaskIDNotFound with default headers values
func NewDeleteAPIV10PeerReviewsTaskIDNotFound() *DeleteAPIV10PeerReviewsTaskIDNotFound {
	return &DeleteAPIV10PeerReviewsTaskIDNotFound{}
}

/*DeleteAPIV10PeerReviewsTaskIDNotFound handles this case with default header values.

The specified resource was not found
*/
type DeleteAPIV10PeerReviewsTaskIDNotFound struct {
	Payload *models.Error
}

func (o *DeleteAPIV10PeerReviewsTaskIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v1.0/peer-reviews/{task_id}][%d] deleteApiV10PeerReviewsTaskIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteAPIV10PeerReviewsTaskIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
