// Code generated by go-swagger; DO NOT EDIT.

package peer_reviews

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIV10PeerReviewsTaskIDParams creates a new GetAPIV10PeerReviewsTaskIDParams object
// with the default values initialized.
func NewGetAPIV10PeerReviewsTaskIDParams() *GetAPIV10PeerReviewsTaskIDParams {
	var ()
	return &GetAPIV10PeerReviewsTaskIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV10PeerReviewsTaskIDParamsWithTimeout creates a new GetAPIV10PeerReviewsTaskIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV10PeerReviewsTaskIDParamsWithTimeout(timeout time.Duration) *GetAPIV10PeerReviewsTaskIDParams {
	var ()
	return &GetAPIV10PeerReviewsTaskIDParams{

		timeout: timeout,
	}
}

// NewGetAPIV10PeerReviewsTaskIDParamsWithContext creates a new GetAPIV10PeerReviewsTaskIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV10PeerReviewsTaskIDParamsWithContext(ctx context.Context) *GetAPIV10PeerReviewsTaskIDParams {
	var ()
	return &GetAPIV10PeerReviewsTaskIDParams{

		Context: ctx,
	}
}

// NewGetAPIV10PeerReviewsTaskIDParamsWithHTTPClient creates a new GetAPIV10PeerReviewsTaskIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV10PeerReviewsTaskIDParamsWithHTTPClient(client *http.Client) *GetAPIV10PeerReviewsTaskIDParams {
	var ()
	return &GetAPIV10PeerReviewsTaskIDParams{
		HTTPClient: client,
	}
}

/*GetAPIV10PeerReviewsTaskIDParams contains all the parameters to send to the API endpoint
for the get API v10 peer reviews task ID operation typically these are written to a http.Request
*/
type GetAPIV10PeerReviewsTaskIDParams struct {

	/*TaskID
	  PeerReview task ID.

	*/
	TaskID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v10 peer reviews task ID params
func (o *GetAPIV10PeerReviewsTaskIDParams) WithTimeout(timeout time.Duration) *GetAPIV10PeerReviewsTaskIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v10 peer reviews task ID params
func (o *GetAPIV10PeerReviewsTaskIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v10 peer reviews task ID params
func (o *GetAPIV10PeerReviewsTaskIDParams) WithContext(ctx context.Context) *GetAPIV10PeerReviewsTaskIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v10 peer reviews task ID params
func (o *GetAPIV10PeerReviewsTaskIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v10 peer reviews task ID params
func (o *GetAPIV10PeerReviewsTaskIDParams) WithHTTPClient(client *http.Client) *GetAPIV10PeerReviewsTaskIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v10 peer reviews task ID params
func (o *GetAPIV10PeerReviewsTaskIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskID adds the taskID to the get API v10 peer reviews task ID params
func (o *GetAPIV10PeerReviewsTaskIDParams) WithTaskID(taskID int64) *GetAPIV10PeerReviewsTaskIDParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get API v10 peer reviews task ID params
func (o *GetAPIV10PeerReviewsTaskIDParams) SetTaskID(taskID int64) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV10PeerReviewsTaskIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param task_id
	if err := r.SetPathParam("task_id", swag.FormatInt64(o.TaskID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
