// Code generated by go-swagger; DO NOT EDIT.

package peer_reviews

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// PostAPIV10PeerReviewsReader is a Reader for the PostAPIV10PeerReviews structure.
type PostAPIV10PeerReviewsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV10PeerReviewsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAPIV10PeerReviewsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostAPIV10PeerReviewsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostAPIV10PeerReviewsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostAPIV10PeerReviewsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAPIV10PeerReviewsOK creates a PostAPIV10PeerReviewsOK with default headers values
func NewPostAPIV10PeerReviewsOK() *PostAPIV10PeerReviewsOK {
	return &PostAPIV10PeerReviewsOK{}
}

/*PostAPIV10PeerReviewsOK handles this case with default header values.

successful operation
*/
type PostAPIV10PeerReviewsOK struct {
	Payload *models.PeerReviewTask
}

func (o *PostAPIV10PeerReviewsOK) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/peer-reviews][%d] postApiV10PeerReviewsOK  %+v", 200, o.Payload)
}

func (o *PostAPIV10PeerReviewsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeerReviewTask)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10PeerReviewsUnauthorized creates a PostAPIV10PeerReviewsUnauthorized with default headers values
func NewPostAPIV10PeerReviewsUnauthorized() *PostAPIV10PeerReviewsUnauthorized {
	return &PostAPIV10PeerReviewsUnauthorized{}
}

/*PostAPIV10PeerReviewsUnauthorized handles this case with default header values.

Unauthorized
*/
type PostAPIV10PeerReviewsUnauthorized struct {
	Payload *models.Error
}

func (o *PostAPIV10PeerReviewsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/peer-reviews][%d] postApiV10PeerReviewsUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAPIV10PeerReviewsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10PeerReviewsForbidden creates a PostAPIV10PeerReviewsForbidden with default headers values
func NewPostAPIV10PeerReviewsForbidden() *PostAPIV10PeerReviewsForbidden {
	return &PostAPIV10PeerReviewsForbidden{}
}

/*PostAPIV10PeerReviewsForbidden handles this case with default header values.

Access Denied
*/
type PostAPIV10PeerReviewsForbidden struct {
	Payload *models.Error
}

func (o *PostAPIV10PeerReviewsForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/peer-reviews][%d] postApiV10PeerReviewsForbidden  %+v", 403, o.Payload)
}

func (o *PostAPIV10PeerReviewsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10PeerReviewsNotFound creates a PostAPIV10PeerReviewsNotFound with default headers values
func NewPostAPIV10PeerReviewsNotFound() *PostAPIV10PeerReviewsNotFound {
	return &PostAPIV10PeerReviewsNotFound{}
}

/*PostAPIV10PeerReviewsNotFound handles this case with default header values.

The specified resource was not found
*/
type PostAPIV10PeerReviewsNotFound struct {
	Payload *models.Error
}

func (o *PostAPIV10PeerReviewsNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/peer-reviews][%d] postApiV10PeerReviewsNotFound  %+v", 404, o.Payload)
}

func (o *PostAPIV10PeerReviewsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
