// Code generated by go-swagger; DO NOT EDIT.

package peer_reviews

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// NewPostAPIV10PeerReviewsTaskIDParams creates a new PostAPIV10PeerReviewsTaskIDParams object
// with the default values initialized.
func NewPostAPIV10PeerReviewsTaskIDParams() *PostAPIV10PeerReviewsTaskIDParams {
	var ()
	return &PostAPIV10PeerReviewsTaskIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV10PeerReviewsTaskIDParamsWithTimeout creates a new PostAPIV10PeerReviewsTaskIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV10PeerReviewsTaskIDParamsWithTimeout(timeout time.Duration) *PostAPIV10PeerReviewsTaskIDParams {
	var ()
	return &PostAPIV10PeerReviewsTaskIDParams{

		timeout: timeout,
	}
}

// NewPostAPIV10PeerReviewsTaskIDParamsWithContext creates a new PostAPIV10PeerReviewsTaskIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV10PeerReviewsTaskIDParamsWithContext(ctx context.Context) *PostAPIV10PeerReviewsTaskIDParams {
	var ()
	return &PostAPIV10PeerReviewsTaskIDParams{

		Context: ctx,
	}
}

// NewPostAPIV10PeerReviewsTaskIDParamsWithHTTPClient creates a new PostAPIV10PeerReviewsTaskIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV10PeerReviewsTaskIDParamsWithHTTPClient(client *http.Client) *PostAPIV10PeerReviewsTaskIDParams {
	var ()
	return &PostAPIV10PeerReviewsTaskIDParams{
		HTTPClient: client,
	}
}

/*PostAPIV10PeerReviewsTaskIDParams contains all the parameters to send to the API endpoint
for the post API v10 peer reviews task ID operation typically these are written to a http.Request
*/
type PostAPIV10PeerReviewsTaskIDParams struct {

	/*PeerReviewTask
	  PeerReview task.

	*/
	PeerReviewTask *models.PeerReviewTask
	/*TaskID
	  PeerReview task ID.

	*/
	TaskID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API v10 peer reviews task ID params
func (o *PostAPIV10PeerReviewsTaskIDParams) WithTimeout(timeout time.Duration) *PostAPIV10PeerReviewsTaskIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v10 peer reviews task ID params
func (o *PostAPIV10PeerReviewsTaskIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v10 peer reviews task ID params
func (o *PostAPIV10PeerReviewsTaskIDParams) WithContext(ctx context.Context) *PostAPIV10PeerReviewsTaskIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v10 peer reviews task ID params
func (o *PostAPIV10PeerReviewsTaskIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v10 peer reviews task ID params
func (o *PostAPIV10PeerReviewsTaskIDParams) WithHTTPClient(client *http.Client) *PostAPIV10PeerReviewsTaskIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v10 peer reviews task ID params
func (o *PostAPIV10PeerReviewsTaskIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPeerReviewTask adds the peerReviewTask to the post API v10 peer reviews task ID params
func (o *PostAPIV10PeerReviewsTaskIDParams) WithPeerReviewTask(peerReviewTask *models.PeerReviewTask) *PostAPIV10PeerReviewsTaskIDParams {
	o.SetPeerReviewTask(peerReviewTask)
	return o
}

// SetPeerReviewTask adds the peerReviewTask to the post API v10 peer reviews task ID params
func (o *PostAPIV10PeerReviewsTaskIDParams) SetPeerReviewTask(peerReviewTask *models.PeerReviewTask) {
	o.PeerReviewTask = peerReviewTask
}

// WithTaskID adds the taskID to the post API v10 peer reviews task ID params
func (o *PostAPIV10PeerReviewsTaskIDParams) WithTaskID(taskID int64) *PostAPIV10PeerReviewsTaskIDParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the post API v10 peer reviews task ID params
func (o *PostAPIV10PeerReviewsTaskIDParams) SetTaskID(taskID int64) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV10PeerReviewsTaskIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PeerReviewTask != nil {
		if err := r.SetBodyParam(o.PeerReviewTask); err != nil {
			return err
		}
	}

	// path param task_id
	if err := r.SetPathParam("task_id", swag.FormatInt64(o.TaskID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
