// Code generated by go-swagger; DO NOT EDIT.

package affiliations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAPIV10AffiliationsTaskIDParams creates a new DeleteAPIV10AffiliationsTaskIDParams object
// with the default values initialized.
func NewDeleteAPIV10AffiliationsTaskIDParams() *DeleteAPIV10AffiliationsTaskIDParams {
	var ()
	return &DeleteAPIV10AffiliationsTaskIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV10AffiliationsTaskIDParamsWithTimeout creates a new DeleteAPIV10AffiliationsTaskIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPIV10AffiliationsTaskIDParamsWithTimeout(timeout time.Duration) *DeleteAPIV10AffiliationsTaskIDParams {
	var ()
	return &DeleteAPIV10AffiliationsTaskIDParams{

		timeout: timeout,
	}
}

// NewDeleteAPIV10AffiliationsTaskIDParamsWithContext creates a new DeleteAPIV10AffiliationsTaskIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPIV10AffiliationsTaskIDParamsWithContext(ctx context.Context) *DeleteAPIV10AffiliationsTaskIDParams {
	var ()
	return &DeleteAPIV10AffiliationsTaskIDParams{

		Context: ctx,
	}
}

// NewDeleteAPIV10AffiliationsTaskIDParamsWithHTTPClient creates a new DeleteAPIV10AffiliationsTaskIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPIV10AffiliationsTaskIDParamsWithHTTPClient(client *http.Client) *DeleteAPIV10AffiliationsTaskIDParams {
	var ()
	return &DeleteAPIV10AffiliationsTaskIDParams{
		HTTPClient: client,
	}
}

/*DeleteAPIV10AffiliationsTaskIDParams contains all the parameters to send to the API endpoint
for the delete API v10 affiliations task ID operation typically these are written to a http.Request
*/
type DeleteAPIV10AffiliationsTaskIDParams struct {

	/*TaskID
	  Affiliation task ID.

	*/
	TaskID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete API v10 affiliations task ID params
func (o *DeleteAPIV10AffiliationsTaskIDParams) WithTimeout(timeout time.Duration) *DeleteAPIV10AffiliationsTaskIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v10 affiliations task ID params
func (o *DeleteAPIV10AffiliationsTaskIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v10 affiliations task ID params
func (o *DeleteAPIV10AffiliationsTaskIDParams) WithContext(ctx context.Context) *DeleteAPIV10AffiliationsTaskIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v10 affiliations task ID params
func (o *DeleteAPIV10AffiliationsTaskIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v10 affiliations task ID params
func (o *DeleteAPIV10AffiliationsTaskIDParams) WithHTTPClient(client *http.Client) *DeleteAPIV10AffiliationsTaskIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v10 affiliations task ID params
func (o *DeleteAPIV10AffiliationsTaskIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskID adds the taskID to the delete API v10 affiliations task ID params
func (o *DeleteAPIV10AffiliationsTaskIDParams) WithTaskID(taskID int64) *DeleteAPIV10AffiliationsTaskIDParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the delete API v10 affiliations task ID params
func (o *DeleteAPIV10AffiliationsTaskIDParams) SetTaskID(taskID int64) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV10AffiliationsTaskIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param task_id
	if err := r.SetPathParam("task_id", swag.FormatInt64(o.TaskID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
