// Code generated by go-swagger; DO NOT EDIT.

package affiliations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// GetAPIV10AffiliationsTaskIDReader is a Reader for the GetAPIV10AffiliationsTaskID structure.
type GetAPIV10AffiliationsTaskIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV10AffiliationsTaskIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV10AffiliationsTaskIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetAPIV10AffiliationsTaskIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAPIV10AffiliationsTaskIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetAPIV10AffiliationsTaskIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV10AffiliationsTaskIDOK creates a GetAPIV10AffiliationsTaskIDOK with default headers values
func NewGetAPIV10AffiliationsTaskIDOK() *GetAPIV10AffiliationsTaskIDOK {
	return &GetAPIV10AffiliationsTaskIDOK{}
}

/*GetAPIV10AffiliationsTaskIDOK handles this case with default header values.

successful operation
*/
type GetAPIV10AffiliationsTaskIDOK struct {
	Payload *models.AffiliationTask
}

func (o *GetAPIV10AffiliationsTaskIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/affiliations/{task_id}][%d] getApiV10AffiliationsTaskIdOK  %+v", 200, o.Payload)
}

func (o *GetAPIV10AffiliationsTaskIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AffiliationTask)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV10AffiliationsTaskIDUnauthorized creates a GetAPIV10AffiliationsTaskIDUnauthorized with default headers values
func NewGetAPIV10AffiliationsTaskIDUnauthorized() *GetAPIV10AffiliationsTaskIDUnauthorized {
	return &GetAPIV10AffiliationsTaskIDUnauthorized{}
}

/*GetAPIV10AffiliationsTaskIDUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAPIV10AffiliationsTaskIDUnauthorized struct {
	Payload *models.Error
}

func (o *GetAPIV10AffiliationsTaskIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/affiliations/{task_id}][%d] getApiV10AffiliationsTaskIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAPIV10AffiliationsTaskIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV10AffiliationsTaskIDForbidden creates a GetAPIV10AffiliationsTaskIDForbidden with default headers values
func NewGetAPIV10AffiliationsTaskIDForbidden() *GetAPIV10AffiliationsTaskIDForbidden {
	return &GetAPIV10AffiliationsTaskIDForbidden{}
}

/*GetAPIV10AffiliationsTaskIDForbidden handles this case with default header values.

Access Denied
*/
type GetAPIV10AffiliationsTaskIDForbidden struct {
	Payload *models.Error
}

func (o *GetAPIV10AffiliationsTaskIDForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/affiliations/{task_id}][%d] getApiV10AffiliationsTaskIdForbidden  %+v", 403, o.Payload)
}

func (o *GetAPIV10AffiliationsTaskIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV10AffiliationsTaskIDNotFound creates a GetAPIV10AffiliationsTaskIDNotFound with default headers values
func NewGetAPIV10AffiliationsTaskIDNotFound() *GetAPIV10AffiliationsTaskIDNotFound {
	return &GetAPIV10AffiliationsTaskIDNotFound{}
}

/*GetAPIV10AffiliationsTaskIDNotFound handles this case with default header values.

The specified resource was not found
*/
type GetAPIV10AffiliationsTaskIDNotFound struct {
	Payload *models.Error
}

func (o *GetAPIV10AffiliationsTaskIDNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/affiliations/{task_id}][%d] getApiV10AffiliationsTaskIdNotFound  %+v", 404, o.Payload)
}

func (o *GetAPIV10AffiliationsTaskIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
