// Code generated by go-swagger; DO NOT EDIT.

package affiliations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIV10AffiliationsTaskIDParams creates a new GetAPIV10AffiliationsTaskIDParams object
// with the default values initialized.
func NewGetAPIV10AffiliationsTaskIDParams() *GetAPIV10AffiliationsTaskIDParams {
	var ()
	return &GetAPIV10AffiliationsTaskIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV10AffiliationsTaskIDParamsWithTimeout creates a new GetAPIV10AffiliationsTaskIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV10AffiliationsTaskIDParamsWithTimeout(timeout time.Duration) *GetAPIV10AffiliationsTaskIDParams {
	var ()
	return &GetAPIV10AffiliationsTaskIDParams{

		timeout: timeout,
	}
}

// NewGetAPIV10AffiliationsTaskIDParamsWithContext creates a new GetAPIV10AffiliationsTaskIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV10AffiliationsTaskIDParamsWithContext(ctx context.Context) *GetAPIV10AffiliationsTaskIDParams {
	var ()
	return &GetAPIV10AffiliationsTaskIDParams{

		Context: ctx,
	}
}

// NewGetAPIV10AffiliationsTaskIDParamsWithHTTPClient creates a new GetAPIV10AffiliationsTaskIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV10AffiliationsTaskIDParamsWithHTTPClient(client *http.Client) *GetAPIV10AffiliationsTaskIDParams {
	var ()
	return &GetAPIV10AffiliationsTaskIDParams{
		HTTPClient: client,
	}
}

/*GetAPIV10AffiliationsTaskIDParams contains all the parameters to send to the API endpoint
for the get API v10 affiliations task ID operation typically these are written to a http.Request
*/
type GetAPIV10AffiliationsTaskIDParams struct {

	/*TaskID
	  Affiliation task ID.

	*/
	TaskID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v10 affiliations task ID params
func (o *GetAPIV10AffiliationsTaskIDParams) WithTimeout(timeout time.Duration) *GetAPIV10AffiliationsTaskIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v10 affiliations task ID params
func (o *GetAPIV10AffiliationsTaskIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v10 affiliations task ID params
func (o *GetAPIV10AffiliationsTaskIDParams) WithContext(ctx context.Context) *GetAPIV10AffiliationsTaskIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v10 affiliations task ID params
func (o *GetAPIV10AffiliationsTaskIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v10 affiliations task ID params
func (o *GetAPIV10AffiliationsTaskIDParams) WithHTTPClient(client *http.Client) *GetAPIV10AffiliationsTaskIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v10 affiliations task ID params
func (o *GetAPIV10AffiliationsTaskIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskID adds the taskID to the get API v10 affiliations task ID params
func (o *GetAPIV10AffiliationsTaskIDParams) WithTaskID(taskID int64) *GetAPIV10AffiliationsTaskIDParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get API v10 affiliations task ID params
func (o *GetAPIV10AffiliationsTaskIDParams) SetTaskID(taskID int64) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV10AffiliationsTaskIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param task_id
	if err := r.SetPathParam("task_id", swag.FormatInt64(o.TaskID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
