// Code generated by go-swagger; DO NOT EDIT.

package affiliations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// NewPostAPIV10AffiliationsParams creates a new PostAPIV10AffiliationsParams object
// with the default values initialized.
func NewPostAPIV10AffiliationsParams() *PostAPIV10AffiliationsParams {
	var ()
	return &PostAPIV10AffiliationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV10AffiliationsParamsWithTimeout creates a new PostAPIV10AffiliationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV10AffiliationsParamsWithTimeout(timeout time.Duration) *PostAPIV10AffiliationsParams {
	var ()
	return &PostAPIV10AffiliationsParams{

		timeout: timeout,
	}
}

// NewPostAPIV10AffiliationsParamsWithContext creates a new PostAPIV10AffiliationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV10AffiliationsParamsWithContext(ctx context.Context) *PostAPIV10AffiliationsParams {
	var ()
	return &PostAPIV10AffiliationsParams{

		Context: ctx,
	}
}

// NewPostAPIV10AffiliationsParamsWithHTTPClient creates a new PostAPIV10AffiliationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV10AffiliationsParamsWithHTTPClient(client *http.Client) *PostAPIV10AffiliationsParams {
	var ()
	return &PostAPIV10AffiliationsParams{
		HTTPClient: client,
	}
}

/*PostAPIV10AffiliationsParams contains all the parameters to send to the API endpoint
for the post API v10 affiliations operation typically these are written to a http.Request
*/
type PostAPIV10AffiliationsParams struct {

	/*Body
	  Affiliation task.

	*/
	Body *models.AffiliationTask
	/*Filename
	  The batch process filename.

	*/
	Filename *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API v10 affiliations params
func (o *PostAPIV10AffiliationsParams) WithTimeout(timeout time.Duration) *PostAPIV10AffiliationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v10 affiliations params
func (o *PostAPIV10AffiliationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v10 affiliations params
func (o *PostAPIV10AffiliationsParams) WithContext(ctx context.Context) *PostAPIV10AffiliationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v10 affiliations params
func (o *PostAPIV10AffiliationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v10 affiliations params
func (o *PostAPIV10AffiliationsParams) WithHTTPClient(client *http.Client) *PostAPIV10AffiliationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v10 affiliations params
func (o *PostAPIV10AffiliationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API v10 affiliations params
func (o *PostAPIV10AffiliationsParams) WithBody(body *models.AffiliationTask) *PostAPIV10AffiliationsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API v10 affiliations params
func (o *PostAPIV10AffiliationsParams) SetBody(body *models.AffiliationTask) {
	o.Body = body
}

// WithFilename adds the filename to the post API v10 affiliations params
func (o *PostAPIV10AffiliationsParams) WithFilename(filename *string) *PostAPIV10AffiliationsParams {
	o.SetFilename(filename)
	return o
}

// SetFilename adds the filename to the post API v10 affiliations params
func (o *PostAPIV10AffiliationsParams) SetFilename(filename *string) {
	o.Filename = filename
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV10AffiliationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Filename != nil {

		// query param filename
		var qrFilename string
		if o.Filename != nil {
			qrFilename = *o.Filename
		}
		qFilename := qrFilename
		if qFilename != "" {
			if err := r.SetQueryParam("filename", qFilename); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
