// Code generated by go-swagger; DO NOT EDIT.

package affiliations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// PostAPIV10AffiliationsTaskIDReader is a Reader for the PostAPIV10AffiliationsTaskID structure.
type PostAPIV10AffiliationsTaskIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV10AffiliationsTaskIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAPIV10AffiliationsTaskIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostAPIV10AffiliationsTaskIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostAPIV10AffiliationsTaskIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostAPIV10AffiliationsTaskIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAPIV10AffiliationsTaskIDOK creates a PostAPIV10AffiliationsTaskIDOK with default headers values
func NewPostAPIV10AffiliationsTaskIDOK() *PostAPIV10AffiliationsTaskIDOK {
	return &PostAPIV10AffiliationsTaskIDOK{}
}

/*PostAPIV10AffiliationsTaskIDOK handles this case with default header values.

successful operation
*/
type PostAPIV10AffiliationsTaskIDOK struct {
	Payload *models.AffiliationTask
}

func (o *PostAPIV10AffiliationsTaskIDOK) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/affiliations/{task_id}][%d] postApiV10AffiliationsTaskIdOK  %+v", 200, o.Payload)
}

func (o *PostAPIV10AffiliationsTaskIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AffiliationTask)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10AffiliationsTaskIDUnauthorized creates a PostAPIV10AffiliationsTaskIDUnauthorized with default headers values
func NewPostAPIV10AffiliationsTaskIDUnauthorized() *PostAPIV10AffiliationsTaskIDUnauthorized {
	return &PostAPIV10AffiliationsTaskIDUnauthorized{}
}

/*PostAPIV10AffiliationsTaskIDUnauthorized handles this case with default header values.

Unauthorized
*/
type PostAPIV10AffiliationsTaskIDUnauthorized struct {
	Payload *models.Error
}

func (o *PostAPIV10AffiliationsTaskIDUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/affiliations/{task_id}][%d] postApiV10AffiliationsTaskIdUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAPIV10AffiliationsTaskIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10AffiliationsTaskIDForbidden creates a PostAPIV10AffiliationsTaskIDForbidden with default headers values
func NewPostAPIV10AffiliationsTaskIDForbidden() *PostAPIV10AffiliationsTaskIDForbidden {
	return &PostAPIV10AffiliationsTaskIDForbidden{}
}

/*PostAPIV10AffiliationsTaskIDForbidden handles this case with default header values.

Access Denied
*/
type PostAPIV10AffiliationsTaskIDForbidden struct {
	Payload *models.Error
}

func (o *PostAPIV10AffiliationsTaskIDForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/affiliations/{task_id}][%d] postApiV10AffiliationsTaskIdForbidden  %+v", 403, o.Payload)
}

func (o *PostAPIV10AffiliationsTaskIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10AffiliationsTaskIDNotFound creates a PostAPIV10AffiliationsTaskIDNotFound with default headers values
func NewPostAPIV10AffiliationsTaskIDNotFound() *PostAPIV10AffiliationsTaskIDNotFound {
	return &PostAPIV10AffiliationsTaskIDNotFound{}
}

/*PostAPIV10AffiliationsTaskIDNotFound handles this case with default header values.

The specified resource was not found
*/
type PostAPIV10AffiliationsTaskIDNotFound struct {
	Payload *models.Error
}

func (o *PostAPIV10AffiliationsTaskIDNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/affiliations/{task_id}][%d] postApiV10AffiliationsTaskIdNotFound  %+v", 404, o.Payload)
}

func (o *PostAPIV10AffiliationsTaskIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
