// Code generated by go-swagger; DO NOT EDIT.

package affiliations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nad2000/uoa-orcidhub/models"
)

// PostAPIV10AffiliationsReader is a Reader for the PostAPIV10Affiliations structure.
type PostAPIV10AffiliationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV10AffiliationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAPIV10AffiliationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostAPIV10AffiliationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostAPIV10AffiliationsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostAPIV10AffiliationsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAPIV10AffiliationsOK creates a PostAPIV10AffiliationsOK with default headers values
func NewPostAPIV10AffiliationsOK() *PostAPIV10AffiliationsOK {
	return &PostAPIV10AffiliationsOK{}
}

/*PostAPIV10AffiliationsOK handles this case with default header values.

successful operation
*/
type PostAPIV10AffiliationsOK struct {
	Payload *models.AffiliationTask
}

func (o *PostAPIV10AffiliationsOK) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/affiliations][%d] postApiV10AffiliationsOK  %+v", 200, o.Payload)
}

func (o *PostAPIV10AffiliationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AffiliationTask)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10AffiliationsUnauthorized creates a PostAPIV10AffiliationsUnauthorized with default headers values
func NewPostAPIV10AffiliationsUnauthorized() *PostAPIV10AffiliationsUnauthorized {
	return &PostAPIV10AffiliationsUnauthorized{}
}

/*PostAPIV10AffiliationsUnauthorized handles this case with default header values.

Unauthorized
*/
type PostAPIV10AffiliationsUnauthorized struct {
	Payload *models.Error
}

func (o *PostAPIV10AffiliationsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/affiliations][%d] postApiV10AffiliationsUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAPIV10AffiliationsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10AffiliationsForbidden creates a PostAPIV10AffiliationsForbidden with default headers values
func NewPostAPIV10AffiliationsForbidden() *PostAPIV10AffiliationsForbidden {
	return &PostAPIV10AffiliationsForbidden{}
}

/*PostAPIV10AffiliationsForbidden handles this case with default header values.

Access Denied
*/
type PostAPIV10AffiliationsForbidden struct {
	Payload *models.Error
}

func (o *PostAPIV10AffiliationsForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/affiliations][%d] postApiV10AffiliationsForbidden  %+v", 403, o.Payload)
}

func (o *PostAPIV10AffiliationsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10AffiliationsNotFound creates a PostAPIV10AffiliationsNotFound with default headers values
func NewPostAPIV10AffiliationsNotFound() *PostAPIV10AffiliationsNotFound {
	return &PostAPIV10AffiliationsNotFound{}
}

/*PostAPIV10AffiliationsNotFound handles this case with default header values.

The specified resource was not found
*/
type PostAPIV10AffiliationsNotFound struct {
	Payload *models.Error
}

func (o *PostAPIV10AffiliationsNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/affiliations][%d] postApiV10AffiliationsNotFound  %+v", 404, o.Payload)
}

func (o *PostAPIV10AffiliationsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
