// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AffiliationTask affiliation task
// swagger:model AffiliationTask
type AffiliationTask struct {

	// completed at
	// Format: date-time
	CompletedAt strfmt.DateTime `json:"completed-at,omitempty"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created-at,omitempty"`

	// expires at
	// Format: date-time
	ExpiresAt strfmt.DateTime `json:"expires-at,omitempty"`

	// filename
	Filename string `json:"filename,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// records
	Records []*AffiliationTaskRecord `json:"records"`

	// task type
	// Enum: [AFFILIATION FUNDING]
	TaskType string `json:"task-type,omitempty"`
}

// Validate validates this affiliation task
func (m *AffiliationTask) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompletedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpiresAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecords(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTaskType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AffiliationTask) validateCompletedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CompletedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("completed-at", "body", "date-time", m.CompletedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AffiliationTask) validateCreatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created-at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AffiliationTask) validateExpiresAt(formats strfmt.Registry) error {

	if swag.IsZero(m.ExpiresAt) { // not required
		return nil
	}

	if err := validate.FormatOf("expires-at", "body", "date-time", m.ExpiresAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AffiliationTask) validateRecords(formats strfmt.Registry) error {

	if swag.IsZero(m.Records) { // not required
		return nil
	}

	for i := 0; i < len(m.Records); i++ {
		if swag.IsZero(m.Records[i]) { // not required
			continue
		}

		if m.Records[i] != nil {
			if err := m.Records[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("records" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var affiliationTaskTypeTaskTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["AFFILIATION","FUNDING"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		affiliationTaskTypeTaskTypePropEnum = append(affiliationTaskTypeTaskTypePropEnum, v)
	}
}

const (

	// AffiliationTaskTaskTypeAFFILIATION captures enum value "AFFILIATION"
	AffiliationTaskTaskTypeAFFILIATION string = "AFFILIATION"

	// AffiliationTaskTaskTypeFUNDING captures enum value "FUNDING"
	AffiliationTaskTaskTypeFUNDING string = "FUNDING"
)

// prop value enum
func (m *AffiliationTask) validateTaskTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, affiliationTaskTypeTaskTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *AffiliationTask) validateTaskType(formats strfmt.Registry) error {

	if swag.IsZero(m.TaskType) { // not required
		return nil
	}

	// value enum
	if err := m.validateTaskTypeEnum("task-type", "body", m.TaskType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AffiliationTask) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AffiliationTask) UnmarshalBinary(b []byte) error {
	var res AffiliationTask
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
