// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PeerReviewTask peer review task
// swagger:model PeerReviewTask
type PeerReviewTask struct {

	// completed at
	// Format: date-time
	CompletedAt strfmt.DateTime `json:"completed-at,omitempty"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created-at,omitempty"`

	// expires at
	// Format: date-time
	ExpiresAt strfmt.DateTime `json:"expires-at,omitempty"`

	// filename
	Filename string `json:"filename,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// records
	Records []PeerReviewTaskRecord `json:"records"`

	// task type
	// Enum: [peer_review peer_reviewING]
	TaskType string `json:"task-type,omitempty"`
}

// Validate validates this peer review task
func (m *PeerReviewTask) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompletedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpiresAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTaskType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerReviewTask) validateCompletedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CompletedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("completed-at", "body", "date-time", m.CompletedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PeerReviewTask) validateCreatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created-at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PeerReviewTask) validateExpiresAt(formats strfmt.Registry) error {

	if swag.IsZero(m.ExpiresAt) { // not required
		return nil
	}

	if err := validate.FormatOf("expires-at", "body", "date-time", m.ExpiresAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var peerReviewTaskTypeTaskTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["peer_review","peer_reviewING"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		peerReviewTaskTypeTaskTypePropEnum = append(peerReviewTaskTypeTaskTypePropEnum, v)
	}
}

const (

	// PeerReviewTaskTaskTypePeerReview captures enum value "peer_review"
	PeerReviewTaskTaskTypePeerReview string = "peer_review"

	// PeerReviewTaskTaskTypePeerReviewING captures enum value "peer_reviewING"
	PeerReviewTaskTaskTypePeerReviewING string = "peer_reviewING"
)

// prop value enum
func (m *PeerReviewTask) validateTaskTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, peerReviewTaskTypeTaskTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *PeerReviewTask) validateTaskType(formats strfmt.Registry) error {

	if swag.IsZero(m.TaskType) { // not required
		return nil
	}

	// value enum
	if err := m.validateTaskTypeEnum("task-type", "body", m.TaskType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PeerReviewTask) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerReviewTask) UnmarshalBinary(b []byte) error {
	var res PeerReviewTask
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
