// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Task task
// swagger:model Task
type Task struct {

	// completed at
	// Format: date-time
	CompletedAt strfmt.DateTime `json:"completed-at,omitempty"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created-at,omitempty"`

	// expires at
	// Format: date-time
	ExpiresAt strfmt.DateTime `json:"expires-at,omitempty"`

	// filename
	Filename string `json:"filename,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// task type
	// Enum: [AFFILIATION FUNDING PEER_REVIEW WORK]
	TaskType string `json:"task-type,omitempty"`
}

// Validate validates this task
func (m *Task) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompletedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpiresAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTaskType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Task) validateCompletedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CompletedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("completed-at", "body", "date-time", m.CompletedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Task) validateCreatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created-at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Task) validateExpiresAt(formats strfmt.Registry) error {

	if swag.IsZero(m.ExpiresAt) { // not required
		return nil
	}

	if err := validate.FormatOf("expires-at", "body", "date-time", m.ExpiresAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var taskTypeTaskTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["AFFILIATION","FUNDING","PEER_REVIEW","WORK"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		taskTypeTaskTypePropEnum = append(taskTypeTaskTypePropEnum, v)
	}
}

const (

	// TaskTaskTypeAFFILIATION captures enum value "AFFILIATION"
	TaskTaskTypeAFFILIATION string = "AFFILIATION"

	// TaskTaskTypeFUNDING captures enum value "FUNDING"
	TaskTaskTypeFUNDING string = "FUNDING"

	// TaskTaskTypePEERREVIEW captures enum value "PEER_REVIEW"
	TaskTaskTypePEERREVIEW string = "PEER_REVIEW"

	// TaskTaskTypeWORK captures enum value "WORK"
	TaskTaskTypeWORK string = "WORK"
)

// prop value enum
func (m *Task) validateTaskTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, taskTypeTaskTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Task) validateTaskType(formats strfmt.Registry) error {

	if swag.IsZero(m.TaskType) { // not required
		return nil
	}

	// value enum
	if err := m.validateTaskTypeEnum("task-type", "body", m.TaskType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Task) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Task) UnmarshalBinary(b []byte) error {
	var res Task
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
